### ISSUE TITLE
ePPN is returned with multiple values

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#116]
The College of William and Mary identity provider (IdP) returns duplicate values for the ePPN attribute. It will look like this (I've changed the actual username--I can give the details). 
* eppn: user@wm.edu;user@wm.edu

This doesn't break anything, but it is stored as the login_id in the user table. As we do with the mail attribute, we should take the first one that's returned in the case of multiple values.

Here's the full report from PrintDMP2ShibInfo.pl (again, with the actual username changed)
The attributes required (eppn and mail) are being successfully received by this SP.
* eppn: user@wm.edu;user@wm.edu
* mail: user@wm.edu
All the Shibboleth-related information being received by this SP
Shib_Application_ID: dmp2-staging
Shib_Authentication_Instant: 2015-01-07T19:45:57.415Z
Shib_Authentication_Method: urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified
Shib_AuthnContext_Class: urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified
Shib_Identity_Provider: https://idp.wm.edu/idp/shibboleth
Shib_Session_ID: _440a2bbb2f1f3a176165e17382c15c75
Shib_Session_Index: 406ae1a8ee831f452422cf29b9acd0b2281894551fbaed0ec81c543309a4efbf
affiliation: member@wm.edu
cn: Fake User Name
eppn: user@wm.edu;user@wm.edu
givenName: Fake
mail: user@wm.edu
sn: User
unscoped_affiliation: member

**Comment by stephaniesimms** [comment]
deploying to production 8 June 2016
