### ISSUE TITLE
Problems with usage stats

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#118]
A couple of problems with the usage stats. https://dmptool.org/usage
1) The rubrics over the graphs are "No. users joined during the last year" and "No. plans created during last year". One user reported some confusing as to whether this is saying "No users..." or "# users..." The abbreviation is causing some confusion.
2) This may only occur for super-admins like me, but I ran a filter for Berkeley Lab, and the results don't match the graph. Are they supposed to? See attached screenshot. The result for the filtered query is 11 new user, but the graph shows only 3. 

![dmptool-users-lbl](https://user-images.githubusercontent.com/1558172/36813393-44b3116c-1c89-11e8-8d5b-17dabd27fcd4.jpg)

**Comment by stephaniesimms** [comment]
fixing some bugs and redesigning usage stats in roadmap currently
