### ISSUE TITLE
Assigning roles within hierarchy

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#118]
Currently, an admin cannot grant roles to users at sub-institutions. Only admins at the same level can grant roles to users. In this example, I'm logged in as the UCOP admin, and trying to grant admin role to a CDL user:
![roles](https://cloud.githubusercontent.com/assets/1558172/5984271/8b9673b6-a889-11e4-9285-6983e34256fd.png)

**Comment by mxsstrong** [comment]
https://www.pivotaltracker.com/story/show/87332456

**Comment by mxsstrong** [comment]
So an Inst Admin should be able to assign roles in a top-down approach (UCOP can assign roles to CDL but not vice versa) or within the family (UCOP can assign to CDL, CDL can assign roles to NRS).  I would think the former, but wanted to clarify

**Comment by cpwillett** [comment]
Yes, a UCOP inst admin should be able to assign roles to CDL, but not vice versa. And CDL cannot assign roles to NRS.

**Comment by mxsstrong** [comment]
fixed.
