### ISSUE TITLE
Contact form emails not arriving in Freshdesk

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#119]
pwillett [1:21 PM]
It looks like emails from dmptool to uc3@ucop.edu are not being forwarded to Freshdesk. I think it has to do with the "from" address do-not-reply-dmptool@cdlib.org. I'm pretty sure it worked yesterday--not sure what changed.

**Comment by cpwillett** [comment]
Well, that's weird. One email just showed up in Freshdesk at 13:33--almost 2 hours after it was received by the uc3@ucop.edu acct. Not sure what's going on.

**Comment by cpwillett** [comment]
The emails eventually show up in Freshdesk,  after some delay. I'll keep an eye on it to be sure that they all get there, and will reopen this ticket if not.

**Comment by stephaniesimms** [comment]
closing the issue for now. reopen if you notice anything amiss.
