### ISSUE TITLE
Broken link on Community Resources page

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#120]
The following links under "LibGuides" on https://dmptool.org/community_resources are broken or need to be updated:

the link under "California Polytechnic State University" should be:
http://libguides.calpoly.edu/content.php?pid=588633

delete "University of California, Los Angeles" and link

add "University of California, Berkeley" and link:
http://researchdata.berkeley.edu/

the link under "Georgia Institute of Technology" should be:
http://d7.library.gatech.edu/research-data/home

the link under "Massachusetts Institute of Technology" should be:
http://libraries.mit.edu/data-management/

Delete the following link under "Repository Selection Help":
Databib (no longer exists/merged with re3data)

**Comment by stephaniesimms** [comment]
fix deployed on 4 May 16
