### ISSUE TITLE
Add markup to static pages for translation

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#120]
Most static pages need the special markup for translation. Only About and Terms of use have it currently. I will also need to replace any markdown with html.

**Comment by briri** [comment]
Quick Start Guide, Promote the DMPTool and Terms of Use pages have been updated and deployed @stephaniesimms 
please take a look when you have a chance and let me know if you see any issues.

I'll push the others out on Monday and then we can update the translation app.po files.

**Comment by stephaniesimms** [comment]
I made some revisions to the md files in dev to fix some broken links, link formatting, and attempt to standardize spacing, etc. a few pages have some wonky overall formatting that needs attention:

FAQ
- missing <hr> between some questions despite having them in the md file

Quick Start Guide/Help
- missing <hr> and <br> elements in Create plan section despite having them in the md file

Data Mgmt General Guidance
- starting at the 'Security and Storage' section there's some weird indentation in places, missing <hr> and <br> elements

**Comment by stephaniesimms** [comment]
overall formatting looks good now @briri - thanks! below are notes of things that I need to fix before deploying to production. 

FAQ
- routing error for about half of links in first section "About the DMPTool"
- update About page link "About participating" (old URL)

Quick Start Guide
- add space/break before "Write your plan"
- create new screenshots (Stephanie)

**Comment by stephaniesimms** [comment]
pretty and deployed now. closing issue.
