### ISSUE TITLE
New institutions missing from superadmin list of institutions

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#121]
I added Colgate as a new institution this morning. When I go to the list of institutions at
https://dmptool.org/super_admin/orgs (see dmp-institutions.jpg)

it's not included. But if I do a little URL hacking and go to 
https://dmptool.org/org/admin/242/admin_edit (see dmp-colgate.jpg)
the edit page shows up.
![dmp-colgate](https://user-images.githubusercontent.com/1558172/36820333-3280aef0-1ca2-11e8-9fb4-51360121f052.jpg)
![dmp-institutions](https://user-images.githubusercontent.com/1558172/36820334-3296ab4c-1ca2-11e8-9846-499476489d3b.jpg)

**Comment by briri** [comment]
Thanks Perry. I found the issue and will patch the Roadmap codebase.

**Comment by stephaniesimms** [comment]
this is fixed on roadmap stage. will test dmptool once changes are deployed.

**Comment by briri** [comment]
deployed to dmptool-stg

**Comment by stephaniesimms** [comment]
working on dmptool-stg. closing issue.
