### ISSUE TITLE
Institution not listed on admin list of users

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#123]
this is probably also just a superadmin issue, but when I get requests from new institutions to make someone an admin, I need to know if they're affiliated with the institution in the db, or if they're still a "non-partner". The old DMPTool included the institution on this page: https://dmptool.org/org/admin/users/admin_index

![dmptool-userlist](https://user-images.githubusercontent.com/1558172/36863163-c845f47c-1d3d-11e8-82a5-247f36a4c798.jpg)

**Comment by stephaniesimms** [comment]
yes, we should definitely add that. Super Admin features got de-prioritized in the run up to MVP but we'll circle back to those now. thanks for flagging it @cpwillett

**Comment by stephaniesimms** [comment]
issue transferred to roadmap repo to address there 
https://github.com/DMPRoadmap/roadmap/issues/1248

**Comment by stephaniesimms** [comment]
addressed in release https://github.com/DMPRoadmap/roadmap/releases
