### ISSUE TITLE
Shibboleth users with missing first and last name

### ISSUE THREAD

**Issue by mxsstrong** [CDLUC3/dmptool#123]
Users who authenticate via Shibboleth are not being directed to the My Profile page to "register" and complete their user profile.  This is difficult to test as we'll need a way to 1) authenticate as a new user using shibboleth and 2) be able to recreate this scenario (have a sql script to delete user so you can re-run this test for verification)

**Comment by mxsstrong** [comment]
related to Issue #121

**Comment by cpwillett** [comment]
A quick count shows almost 700 users with no firstname or lastname.

**Comment by mxsstrong** [comment]
I believe this was fixed - need to check with @sfisher

**Comment by sfisher** [comment]
I think it's now redirecting back to the my profile page if they don't fill things in.  Basically they can't use the tool until they fill it in.

**Comment by mxsstrong** [comment]
Thanks scott,  that's what I thought.
