### ISSUE TITLE
What's a valid email address when creating account?

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#124]
I wanted to set up an account using LDAP instead of Shib, to see what an unaffiliated user looks like. I entered my gmail acct, but am told "You must enter a valid email address." Perhaps I'm triggering some other error because I have another account or something, but the error message is not helpful. 
![dmptool-validemail](https://user-images.githubusercontent.com/1558172/36863953-006a477a-1d40-11e8-9164-f6446ab9ec94.jpg)

**Comment by stephaniesimms** [comment]
I see you already have an account with this email address. Yes, we need to amend the error message accordingly...

**Comment by stephaniesimms** [comment]
after testing it seems that we need to provide the correct error message here. there's a test account InstRev123 registered with this email address. so the error should say "That email address is already registered." i get the correct error message if I try to create an account with this email and the registered First and Last name, but not if the names are different as in the screenshot above. this may be an edge case to just be aware of. i don't imagine many users will try to create a new account with an existing email and a different name - thoughts @briri ?

**Comment by briri** [comment]
The first and last names are not relevant here. The email address is the only thing that must be unique. I think something else is going on. In Perry's original screenshot, the 'Password' field is in error but displaying a message about the email address. That error message is triggered by JS on the page before the submit button is clicked. My guess is that the password was not valid and its just displaying the wrong message.

**Comment by stephaniesimms** [comment]
that makes more sense @briri - in which case can you just update the error message to say "you must enter a valid password or reset your password?"

**Comment by briri** [comment]
the message has been updated and is already out on the production server. Going to close this one out
