### ISSUE TITLE
FAQ / ask.dmptool.org is read-only 

### ISSUE THREAD

**Issue by mxsstrong** [CDLUC3/dmptool#124]
There seems to be some technical difficulties surrounding the FAQ hosting service we're using.  I will investigate further

**Comment by cpwillett** [comment]
The error message still reads "The site is temporarily read-only. Full access to be restored by March 12."

**Comment by mxsstrong** [comment]
this is becoming more an issue as access has not been restored.  I'm bumping up the priority.

**Comment by cpwillett** [comment]
Yes, it's clear that the Askbot service is no longer viable. We need to find a different solution for FAQ and cancel our subscription to Askbot.
