### ISSUE TITLE
Requesting a list of institutional plans by direct API calls returns public DMPs

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#127]
To reproduce the bug:
1) Log into the DMPTool as institutional admin. We have an institutional admin account available. Choose “Not in list” and log in with:
username: XXXX
password: XXXX

2) Call the following documented API <https://github.com/CDLUC3/dmptool/wiki/API#for-a-list-of-plans-this-api-request-requires-authentication> either by direct CURLing or pasting into the browser:
$ curl -H  "Authorization: Token token=token_number" https://dmptool.org/api/v1/plans

expected result: The call returns all institutional plans with a column for ID number (see related Issue #128) and no public DMPs

actual result: The call returns all public DMPS rather than the institutional ones, and with no ID numbers

This behavior is the same across all platforms.

**Comment by stephaniesimms** [comment]
Revisit issue of private visibility and whether it is appropriate to allow Institutional Admins to request a list of "private" plans. Instead it may be sufficient to include funder and other attributes, but retain plan as private.

**Comment by stephaniesimms** [comment]
Feedback from DMPAdmin-L:
In general, I think I'm usually looking for two types of information from the usage statistics: amount/patterns of usage (which can be anonymous and aggregated) and data that I can use to connect with faculty, either directly or via subject outreach librarians. That second category is where
user names connected at least to funders and maybe with proposal titles, etc. is useful, because I can let the other librarians know who in their departments are using the tool. What would be awesome, but maybe not realistic, is for I or the designated reviewer for a funder template got a notification when a new plan was started, and then we could follow up with the author. One bit of feedback we've gotten from users here is that it's a little impersonal, and they'd rather just come directly to me or another
librarian for help. If we could use usage data to bridge the gap a bit, it would be so helpful.

**Comment by mxsstrong** [comment]
So far institutional admins, they will be able to view public plans, plans they own, and private plans within their institution.  The information displayed will not contain the plan details (such as questions and answers) only plan overview information.

**Comment by winkler4** [comment]
At Penn, the plan overview information, associated with person data, that are public, owned, or private plans within the institution, available only to institutional admins would be sufficient.

**Comment by stephaniesimms** [comment]
This is
