### ISSUE TITLE
Requesting a specific plan by direct API calls fails/returns an error message

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#128]
Because of bug #127 the below stated API calls are unusable, since it is impossible to obtain a correct plan ID (randomly guessing ID is not a solution).

To reproduce the bug:
1) Log into the DMPTool as institutional admin.

2) Call the following documented API https://github.com/CDLUC3/dmptool/wiki/API#for-a-specific-plan-this-api-request-requires-authentication either by direct CURLing or pasting into the browser:
$ curl -H "Authorization: Token token=token_number" https://dmptool.org/api/v1/plans/:id

expected result: The call returns a specific institutional plan (per ID number) 

actual result: The call returns the message "The plan you are looking for doesn't exist" (most of the randomly tested id-numbers don't refer to actual plans).

**Comment by rdhyee** [comment]
I believe I'm running into the same problems: https://gist.github.com/f6339bead9112619a20c.

**Comment by mxsstrong** [comment]
the problem here is that #127 is not returning an id.  we will fix that and this issue will be resolved.
