### ISSUE TITLE
Changes to auto email messages for US en and correct links

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#128]
below is an itemized list of changes to email content for DMPTool

- global note to make sure all email signatures use contact-us URL (dash not underscore)

https://github.com/CDLUC3/dmptool/blob/master/app/views/user_mailer/admin_privileges.html.erb
- <%= raw _('More information about administering the %{tool_name} for users at your organisation is available at the %{help_url}.') %{ :tool_name => tool_name, :help_url => link_to('help for administrators page', help_url)} %>
- in the string above, change spelling to "organization"
- replace help_url with DMPTool Admin guide URL https://github.com/CDLUC3/dmptool/wiki/Help-for-Administrators

https://github.com/CDLUC3/dmptool/blob/master/app/views/user_mailer/api_token_granted_notification.html.erb
- change spelling to "organization"

https://github.com/CDLUC3/dmptool/blob/master/app/views/user_mailer/plan_visibility.html.erb
- change spelling of "Organization: anyone at my organization can view"

https://github.com/CDLUC3/dmptool/blob/master/app/views/user_mailer/welcome_notification.html.erb
- in the following string make sure contact-us (dash not underscore):
    <%= raw(_('%{tool_name} will help you to develop your Data Management Plan. If you have any queries or feedback as you use the tool, please contact us at %{helpdesk_email} or visit %{contact_us}') %{ :tool_name => tool_name, :helpdesk_email => mail_to(helpdesk_email, helpdesk_email, subject: email_subject), :contact_us => link_to(contact_us, contact_us) }) %>

**Comment by briri** [comment]
Hmm. The few I've looked at are in the app.po file. Is there one in particular?

**Comment by stephaniesimms** [comment]
i noticed the admin privileges email contains GB english "organisation" on dmptool stage - and now that i'm looking more carefully at some emails from production i see that i need to update some of the links too

**Comment by stephaniesimms** [comment]
emails look good. closing issue.
