### ISSUE TITLE
Requesting a list of plans with related attributes by direct API calls returns public DMPs

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#129]
To reproduce the bug:
1) Log into the DMPTool as institutional admin. 

2) Call the following documented API https://github.com/CDLUC3/dmptool/wiki/API#for-a-list-of-plans-with-all-related-attributes-this-api-request-requires-authentication either by direct CURLing or pasting into the browser:
$ curl -H "Authorization: Token token=token_number" https://dmptool.org/api/v1/plans_full

expected result: The call returns all institutional plans (related Issue #127) with a column for ID number (related Issue #128), other attribute columns, and no public DMPs

actual result: The call returns all public DMPS rather than the institutional ones, and with no ID numbers

This behavior is the same across all platforms.

**Comment by mxsstrong** [comment]
this API call now returns a list of plans that have institutional visibility.  Similar to what you would see if you are an institutional administrator and viewed Public Plans https://dmp2-dev.cdlib.org/public_dmps
