### ISSUE TITLE
Changing my pw removes my org affiliation

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#131]
When I change my pw on the tab in my profile area and click Save, the action removes my Org affiliation. This is only happening for DMPTool, and not in Roadmap stage.

![screen shot 2018-03-15 at 2 23 47 pm](https://user-images.githubusercontent.com/12703638/37491943-a78b34a2-285c-11e8-836d-6f6d9b0197c0.png)

**Comment by briri** [comment]
this issue should be resolved now

**Comment by stephaniesimms** [comment]
fixed in production. closing issue.
