### ISSUE TITLE
Two notifications for plan feedback to admins

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#132]
Chris Eaker (UTK) reports:

When someone submits a plan for feedback, I have been getting two notifications messages as admin. They are mostly duplicates, but the greeting line is slightly different. Screenshots are attached.
![ce](https://user-images.githubusercontent.com/1558172/37532913-ae1648c4-28fd-11e8-8b84-76d57dfd54c1.png)
![cedcl](https://user-images.githubusercontent.com/1558172/37532914-ae2f2498-28fd-11e8-91bd-e24c6c897ced.png)

**Comment by chriseaker** [comment]
I got duplicates from DMPs submitted by regular users since the changeover to the new version, which got me curious. So I tested it out myself to see if I got dupes when I created a DMP and asked for feedback, and I did. Those are the screenshots above.

**Comment by briri** [comment]
Hi @chriseaker, we're actively working on a related ticket on the Roadmap project (the foundation of the new DMPTool). https://github.com/DMPRoadmap/roadmap/issues/1217

We'll only be sending the feedback email to the the contact listed on the Organization Details page. All org admins will still see the link to the plan though on notifications section of their 'Admin -> Plans' page

**Comment by stephaniesimms** [comment]
this will be fixed in the latest release to dmptool tomorrow. now only the main contact email receives a notice when users submit plans for feedback https://github.com/DMPRoadmap/roadmap/releases/tag/v1.1.2
