### ISSUE TITLE
FSU would like to test a new identity provider

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#134]
Florida State is implementing a new Shib IdP that they'd like to test against the DMPTool (stage). This test IdP isn't registered with Incommon, so it's not included in the XML metadata. They suggest that we manually insert an XML snippet (see attachment) into the XML file. I believe it can go anywhere in the Incommon XML file after the initial elements for signatures and certificates and what-not. The EntityDescriptor elements seem to start around line 56. We would need to turn off the daily updates of the XML file by the Shib Service Provider.
[fsu-shib-dev-metadata.xml.txt](https://github.com/CDLUC3/dmptool/files/1820919/fsu-shib-dev-metadata.xml.txt)

**Comment by briri** [comment]
Hey @cpwillett, 
I added their dev server's entry to our InCommon metadata file but am unable to reach their dev IdP because I'm outside their network. Can you have them try it on their end? They should be able to access the IdP and verify that the roundtrip between their new IdP and our app.

**Comment by cpwillett** [comment]
Looks like it works--thanks @briri. I'll close the ticket.

**Comment by briri** [comment]
Great! Just an FYI that the InCommon metadata file will refresh tonight and that dev IdP will not be in the file. I can readd though if they need to do further testing.

**Comment by cpwillett** [comment]
FSU would like to conduct another test on their stage IdP with the attached Incommon metadata snippet, as was done earlier. Could this be added? Let me know when this can be done, and I'll let them know. Thanks.

**Comment by briri** [comment]
all set Perry. I've updated our InCommon XML file. It looks though like they have an issue on their end and need to register the DMPTool with their Central Authentication Service (CAS).

**Comment by cpwillett** [comment]
FSU would like to add the new snippet (attached) to the Incommon metadata on dmptool-stage. I think this would require deleting the entry for entityID "https://idp.fsu.edu" in the Incommon distribution. Please let me know when this can be done, and I'll let them know. I think this means Thanks.

[idp.fsu.edu.QNA.xml.txt](https://github.com/CDLUC3/dmptool/files/1939239/idp.fsu.edu.QNA.xml.txt)

**Comment by cpwillett** [comment]
Hi Brian,

Sorry to keep coming back to this. Could you reinstall the same snippet from yesterday (attached), and turn off updating again until FSU finishes testing? Thanks.
[idp.fsu.edu.QNA.xml.txt](https://github.com/CDLUC3/dmptool/files/1944613/idp.fsu.edu.QNA.xml.txt)

**Comment by briri** [comment]
I'm not sure how to turn it off Perry. I extended it to 5 days.

________________________________

**Comment by cpwillett** [comment]
Thanks, Brian. That's good enough.

**Comment by cpwillett** [comment]
Hi Brian,
I may be confusing myself. Could you check that you added this snippet? Our contact says that he's getting an error that a previous snippet would have generated. Sorry about the added work. Thanks,

Perry

[idp.fsu.edu.QNA.xml.txt](https://github.com/CDLUC3/dmptool/files/1944695/idp.fsu.edu.QNA.xml.txt)

**Comment by stephaniesimms** [comment]
tracking this in freshdesk. closing issue.
