### ISSUE TITLE
Update ORCID to use the member API

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#135]
Update the ORCID oath config to make use of the member API.

Investigate appropriate workflow for allowing someone to designate a different ORCID id as the PI on a plan. This feature should be upstreamed to DMPRoadmap!

**Comment by briri** [comment]
Great to hear about your plans for DMP Tool! Below are the basic steps of what you will need to do. It’s important to note that if any ORCID iDs and access tokens were collected previously using the public API, those connections will need to be made again once the member API is in place, as the access tokens depend on the client ID they were originally associated with. If you want to have a call to talk more in-depth about this work and any implications, let me know.

The first step would be to request member API sandbox credentials by filling out the form here: https://orcid.org/content/register-client-application-sandbox – ORCID will send you the new member API client ID and client secret within a few days.

You can then use the client ID provided to test the member API with DMP Tool in the sandbox first.
You will want to double check and make sure the integration meets the best practices outlined here: https://members.orcid.org/api/member-api-credentials-check-list

Then, when you feel ready to go to production we would set up a demo call with ORCID to make sure the application is meeting best practices, and then we would switch the sandbox credentials out for production credentials.

**Comment by briri** [comment]
filled out the online registration for the sandbox credentials. 

I think we may need to wait a week or two for the credentials to get to us and then some UAT before we're ready to implement in prod.

**Comment by marisastrong** [comment]
@briri I assume you're working with Sheila Rabun on the ORCID integration but if not, here is her contact information to use when you're ready to move things into production.
Sheila Rabun, MA, MLIS  
ORCID US Community Specialist

**Comment by briri** [comment]
member credentials are working in stage. need to contact ORCID to get production credentials

**Comment by briri** [comment]
Deployed to production.

@mariapraetzellis  - Just noting here that users will need to re-authenticate against ORCID in the future if we want to update their ORCID record with DMP DOIs. This is because we are only using ORCID 'authorize' scope.

"... right now you are using the /authorize scope only. If you add scopes to the integration in the future (such as using /activities/update to write info to a user’s ORCID record), any user who has already connected their ORCID iD with the application will have to do so again to authorize the new scopes."

Since we already have people who have linked their accounts via the public API method we would need to do this anyway. We can introduce an interim page that pops up for users when they log in that describes the new integration and asks them to re-authorize
