### ISSUE TITLE
Cannot create new institution from institutions#index

### ISSUE THREAD

**Issue by der-scheme** [CDLUC3/dmptool#135]
Clicking the "Add New Institution" button from the hierarchy tab in institutions#index will yield the following routing error:

    No route matches [GET] "/5/institutions/new" 

The source of the issue is line 28 in file app/views/institutions/index.html.erb, where the new_institutions_path helper is passed the parameter 5. Removing said parameter will make this error go away.

**Comment by stephaniesimms** [comment]
We disabled the Institution Hierarchy feature. You can read about it here:
https://github.com/CDLUC3/dmptool/wiki/Institution-Hierarchy-Information

**Comment by der-scheme** [comment]
Alright. That is not a good way to do this, though, as I can still achieve my goal by URL manipulation. I suggest `fail`ing in the controller, as well as removing the button (as it is confusing to have a button that will never work).
