### ISSUE TITLE
Update CSS styling of active button

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#136]
Bootstrap applies a blue shadow around the DOM element that currently has focus. This is lost on our app because the buttons have a blue background.

Update the `lib/assets/stylesheets/dmptool.scss` file so that our default shadow color is ??? (@rhu001 what color should we use here?)

related to #89

**Comment by rhu001** [comment]
@briri I am not seeing a blue shadow on my browser so this may be a browser specific characteristic. Why don't we let this ride for now and wait for ITS to conduct their formal review next week and if they pick up on this they may also offer us a solution for fixing.

**Comment by briri** [comment]
closing this one. We got more specific feedback from the accessibility report. Will create a new issue for it
