### ISSUE TITLE
Translations: missing strings for Portuguese

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#144]
**Global issues**
completely missed Quick Start Guide static page
random pieces of Data Mgmt General Guidance
random pieces of FAQ
random pieces of Promote the DMPTool
Most (all?) emails missed
Notification messages all partial and strange (some screenshots below)
Text beside radio buttons and tickboxes

**Itemized things on various pages**

'Learn' in top nav menu
'For Administrators'

![screen shot 2018-04-05 at 10 57 35 am](https://user-images.githubusercontent.com/12703638/38383001-34ad492e-38c0-11e8-8095-e7e96802125e.png)

'More' in DMPTool by the Numbers section on homepage
Remove ?? from this section too

![screen shot 2018-04-05 at 10 49 14 am](https://user-images.githubusercontent.com/12703638/38382535-13c2323e-38bf-11e8-991d-3b63694c05a4.png)

Notice message has funny diacritics - should say 'Nota: Autenticado ..."
Need to translate 'your institutional credentials' ??

![screen shot 2018-04-05 at 10 53 14 am](https://user-images.githubusercontent.com/12703638/38382757-a185bbd6-38bf-11e8-83b7-7bd5d878c7e9.png)

Notice messages half translated - need to evaluate all notice messages

![screen shot 2018-04-05 at 10 59 26 am](https://user-images.githubusercontent.com/12703638/38383113-779a142e-38c0-11e8-83c3-e0459f3772ee.png)
![screen shot 2018-04-05 at 11 12 13 am](https://user-images.githubusercontent.com/12703638/38383771-398820c0-38c2-11e8-8d6c-d783e6bee437.png)

Test beside tickboxes on Create plan page

![screen shot 2018-04-05 at 11 08 05 am](https://user-images.githubusercontent.com/12703638/38383573-b8838320-38c1-11e8-83f5-4be22de434ed.png)

Text beside tickboxes on Project details page
'See the full list' link for guidance selection

![screen shot 2018-04-05 at 11 10 39 am](https://user-images.githubusercontent.com/12703638/38383745-2b518ab4-38c2-11e8-8b09-345f919843a1.png)

Autosave message temporal text 'just now' ... 'less than a minute ago'

![screen shot 2018-04-05 at 11 15 11 am](https://user-images.githubusercontent.com/12703638/38383960-b82c4870-38c2-11e8-8304-bc7516bb4894.png)

Text beside some radio buttons on Share tab

![screen shot 2018-04-05 at 11 19 55 am](https://user-images.githubusercontent.com/12703638/38384211-676eab5c-38c3-11e8-85ef-5b53a1c9def7.png)

Text beside tickboxes on Download tab

![screen shot 2018-04-05 at 11 21 42 am](https://user-images.githubusercontent.com/12703638/38384295-9ca82abe-38c3-11e8-814b-1baf02f32a57.png)

Some headers on static pages (Terms of Use & Privacy e.g.)

![screen shot 2018-04-05 at 11 27 50 am](https://user-images.githubusercontent.com/12703638/38384601-73460258-38c4-11e8-90e6-e0105008e685.png)

Public plans description

![screen shot 2018-04-05 at 11 29 07 am](https://user-images.githubusercontent.com/12703638/38384689-aca3e556-38c4-11e8-998f-a525ab29e8bb.png)

New columns added to Users table

![screen shot 2018-04-05 at 11 34 28 am](https://user-images.githubusercontent.com/12703638/38384940-5eb5aa68-38c5-11e8-83b5-2b06fbba6241.png)

Headings for Edit user privileges modal

![screen shot 2018-04-05 at 11 35 16 am](https://user-images.githubusercontent.com/12703638/38384975-7a19c8c0-38c5-11e8-8cee-731183209e1c.png)

Header and button text for editing user profile

![screen shot 2018-04-05 at 11 36 48 am](https://user-images.githubusercontent.com/12703638/38385061-b4ecbe8a-38c5-11e8-9605-07cd5afc9fad.png)

Header for 'Usage statistics'

![screen shot 2018-04-05 at 11 38 35 am](https://user-images.githubusercontent.com/12703638/38385131-ed4ed31c-38c5-11e8-9430-7e04b0d05175.png)

Missed link text for Templates page 'All' 'Published' etc... but yes for Customization tab links???

![screen shot 2018-04-05 at 11 39 15 am](https://user-images.githubusercontent.com/12703638/38385165-0a739568-38c6-11e8-897a-4a716069acca.png)

![screen shot 2018-04-05 at 11 40 07 am](https://user-images.githubusercontent.com/12703638/38385213-26c2c90a-38c6-11e8-9247-833f754e3709.png)

'Add' and 'Edit' for buttons in template customization

![screen shot 2018-04-05 at 1 53 27 pm](https://user-images.githubusercontent.com/12703638/38391350-d9ce3950-38d8-11e8-974c-126090cdacb7.png)

**Comment by briri** [comment]
Noted Roadmap specific items on the https://github.com/DMPRoadmap/roadmap/issues/1339 ticket.

We will have to address the navigation menu, home page and static page content in the DMPTool customized version of the code.

**Comment by stephaniesimms** [comment]
this is fixed in roadmap now and translation files are updated
