### ISSUE TITLE
How to use the dmptool API to retrieve the pdf, docx, and json versions of a plan?

### ISSUE THREAD

**Issue by rdhyee** [CDLUC3/dmptool#146]
For a given plan, how to use the API to download it in various formats?  For example, I have a plan with the `id` of `16453`.  It is currently private.

From a browser in which I am logged in to dmptool.org, I'm able to retrieve the PDF from

https://dmptool.org/plans/16453.pdf

and the docx version from

https://dmptool.org/plans/16453.docx

However, I'd like to access the pdf, docx, and json formats from the [API](https://github.com/CDLUC3/dmptool/wiki/API).  (I understand that there should be a json format of plan -- is that correct.)

I tried:

```
curl -H  "Authorization: Token token=token_number" https://dmptool.org/plans/16453.pdf
```
but that didn't work.

How can I get the pdf, docx, and json formats (which presumably has the questions and answers) programmatically?

**Comment by mxsstrong** [comment]
https://dmptool.org/api/v1/plans_full/<plan_id> returns plan in JSON format

**Comment by rdhyee** [comment]
I can see that https://dmptool.org/api/v1/plans_full/ returns all the public plans in json format -- 58 of them when I just accessed this URL.  Very useful

However, I don't see how to use the API to access the pdf/docx/json versions of a given plan.  Plan # 16453 is a private one I created.  From a browser in which I'm logged into dmptool.org, I can download  https://dmptool.org/plans/16453.pdf and https://dmptool.org/plans/16453.docx.  But I've not been able to use the API to download the pdf or docx.  I tried

```
curl -H  "Authorization: Token token=token_number" https://dmptool.org/plans/16453.pdf
```

but instead of the PDF, I got a redirect to https://dmptool.org/

**Comment by mxsstrong** [comment]
https://dmptool.org/api/v1/plans_full/ <plan_id>  returns the JSON format of a single plan.  

the other 2 methods to access the PDF and DOCX formats are not available outside of the API.  These are direct method calls which are not set up to be use with the token authentication.  If we need these pages to be available using the token authentication, we will need to make a code change to accommodate.

**Comment by rdhyee** [comment]
@mxsstrong How do I use https://dmptool.org/api/v1/plans_full/ to return the JSON format for plan 16453 (a **private** plan that I authored)? 

A central scenario I'd love to make happen is to let a user in osf.io pull up a list of her plans, pick one of the plans, and send the plan to osf.io.  So, yes, being able to access the PDF, DOCX, **or** JSON versions (the best option) from the API is something I'd need to make the scenario happen (as far as I can see.)

**Comment by sfisher** [comment]
Here is an example of retrieving the json.  Just replace <add-token-here> with your token.

curl -H "Authorization: Token token=<add-token-here>" https://dmptool.org/api/v1/plans_full/16453

As far as getting other formats.  We'd either need to add additional formats to the API or enable token authentication to parts of the non-api application.

**Comment by mxsstrong** [comment]
i'm sorry Raymond, the markdown must have been removing the plan_id from the end of the API method.    Scott provided the proper syntax!  I hope this helps.

**Comment by rdhyee** [comment]
Thanks @sfisher and @mxsstrong -- putting the id at the end was exactly what  I needed.  

If it's not a huge amount of work, making the pdf and docx available would be a nice addition.  Otherwise, if you can point me to where in your code you create the pdf and docx, I might be able to leverage your conversion code to generate the pdf/docx on my own side.

**Comment by mxsstrong** [comment]
Probably would be easier to enable the token authentication or make the other formats available via the api - working with those formats can  be quite tedious.

How soon would you need these formats?

Do you have other non-api method calls that you need exposed?

marisa

**Comment by rdhyee** [comment]
I'm trying to wrap my round of work for COS by the end of November.  But the json output gives me a lot to work with already--> so I'm not stuck. 

Let me think a bit about the question of what other non-api method calls I need.  Off the top of my head, I'd love to have a way of listing only the plans owned by user given a auth token -- right now, I think I'd have to filter on the user's email address.

**Comment by mxsstrong** [comment]
List of plans by user_id - what you would see on the My DMPs page ( a list of your own DMPs)

**Comment by rdhyee** [comment]
Re https://github.com/CDLUC3/dmptool/issues/146#issuecomment-149627300:  Yes I'd like to access from the API:

> List of plans by user_id - what you would see on the My DMPs page ( a list of your own DMPs)

Is that likely to happen in the next month or two?  Or should I plan to ask user for the plan id (at least as a start)?

**Comment by stephaniesimms** [comment]
The calls for a list of plans and plans with attributes are still missing the plan ID:
https://dmptool.org/api/v1/plans
https://dmptool.org/api/v1/plans_full

**Comment by mxsstrong** [comment]
Add the id to the output of the https://dmptool.org/api/v1/plans method.  
Only return private plans (plans owned by the user associated with the AUTH token).  Possibly new API call for plans_owned

**Comment by stephaniesimms** [comment]
new calls deployed to production; wiki updated
