### ISSUE TITLE
Change Heading of the home page

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#154]
High priority recommendation from the UCOP accessibility test:
- The home page heading currently says 'Welcome' with no context for users of assistive technologies. Switch it to read 'Welcome to the DMPTool' or something similar. 
- Twitter & RSS icons have no text for a screen reader
- 'More' links are not descriptive enough for screen readers. They provide no context

**Comment by stephaniesimms** [comment]
- I don't see any text on the Twitter and RSS icons for screen readers.
- 'More' links have text, but one is incorrect. Revise the link for Top 5 Templates to say "View the list of funder requirements"

**Comment by stephaniesimms** [comment]
these things look good now. closing.
