### ISSUE TITLE
Fix accessibility issues on static pages

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#155]
Now that we're using Markdown we need to use the correct heading hierarchy in the same way we do for HTML (e.g. `<h1>` then `<h2>`s, etc.)

Make sure we're using: `#Heading 1`, then `##Heading 2`, etc. 

Adjust SCSS file if necessary to give them the desired font size and weight

We also need to update the links to PDFs and Power Points on the Promote page to give them more context. For example instead of 'Adobe PDF' use 'Posters (PDF)'

**Comment by briri** [comment]
changes made in development branch. Remove the Markdown handler and updated all static page content back over to HTML with correct tags.

**Comment by stephaniesimms** [comment]
markup and tags all good now.
