### ISSUE TITLE
Static pages throw error on DMPTool stage

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#163]
I get the following error when I try to access all static pages while testing on dmptool stage (FAQ, Quick Start Guide, About, Terms...)

![faq-error](https://user-images.githubusercontent.com/12703638/40438798-e01dea98-5e6d-11e8-9ebf-3d585e4f25c7.png)

**Comment by briri** [comment]
removed redcarpet gem as part of Ruby upgrade. We need it in our version for Markdown rendering. Adding back in for DMPTool

**Comment by stephaniesimms** [comment]
working now. closing.
