### ISSUE TITLE
Only return private plans (plans owned by the user associated with the AUTH token).  

### ISSUE THREAD

**Issue by mxsstrong** [CDLUC3/dmptool#164]
Return plans owned by the user associated with the AUTH token.  new API call for plans_owned will return plans owned by a user (authenticated via TOKEN).  The list will include public, institutional, and private plans that the user has created and is the owner.  What you would see on the My DMPs page

**Comment by rdhyee** [comment]
+1 for such an API call.

**Comment by briri** [comment]
https://www.pivotaltracker.com/story/show/107873764

**Comment by rdhyee** [comment]
great to see progress on this front. Any way I can be invited to follow https://www.pivotaltracker.com/story/show/107873764?

**Comment by mxsstrong** [comment]
Hi Raymond,  The pivotal system is for internal developers and I can't provide access to specific stories, it would have to be for the whole DMPTool project defined within.

**Comment by rdhyee** [comment]
I understand, @mxsstrong.

**Comment by mxsstrong** [comment]
hi @rdhyee ,

The 2 following calls are available on our stage server.  Can you please test to ensure these are what you need?  we can then push to production.

https://dmp2-staging.cdlib.org/api/v1/plans_owned
https://dmp2-staging.cdlib.org/api/v1/plans_owned_full

I did a check and all looks good for me.

**Comment by rdhyee** [comment]
Hi @mxsstrong -- I'll take a look.  Thanks for the update.

**Comment by rdhyee** [comment]
I was able to get both

https://dmp2-staging.cdlib.org/api/v1/plans_owned
https://dmp2-staging.cdlib.org/api/v1/plans_owned_full

to work on the staging server in which I created a single private DMP.

**Comment by stephaniesimms** [comment]
new calls deployed to production; wiki updated
