### ISSUE TITLE
New API call to get a list of templates for a specific institution (funders)

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#165]
Return a list of templates (funders) used to create DMPs for a specific institution. New API call for requirements_templates will return template name and created_at date for all public, institutional, and private plans at a specific institution_id.

**Comment by briri** [comment]
Question on security here. My assumptions are as follows, please let me know if I am off base.
- Unauthorized request:  Will return ONLY templates with public visibility
- Authorized request (Institutional admin): Will return templates with public or institutional visibility (for the user's specific institution)
-Authorized request (DMP admin): Will return ALL templates

**Comment by mxsstrong** [comment]
We should probably open up the authorized request at the institutional level to Requirements Editors, and Resource Editors which will return the templates for their institution.  Similar to what they would see when going to the DMP Templates page and/or Customizations page.

**Comment by stephaniesimms** [comment]
The goal is to provide admins with some info about all plans being created at their institutions. Currently they can't get any info about private plans which comprise the majority, so essentially they can't get any meaningful stats about DMPTool use. Anonymized info about private plans, especially template use, would be really useful to them.

For an authorized request, is there any way to return all templates regardless of visibility setting for a given institution?

**Comment by mxsstrong** [comment]
thanks for clarifying the use case Stephanie.  that helps to shape what will be informative for the response.

**Comment by briri** [comment]
Yes, thank you Stephanie.
I will set it up so that an institutional admin also sees private templates for their institution.

**Comment by stephaniesimms** [comment]
Super. That's what we want/need.

**Comment by mxsstrong** [comment]
@stephaniesimms is the created_at date pertain to the plan or the template?  I assume the former.  Also, is this for plans in all states, new, revised, reviewed, submitted, done?

**Comment by stephaniesimms** [comment]
yes, created_at date pertains to the plan. and yes, for plans in all states.

**Comment by briri** [comment]
If the date pertains to the plan then you could end up with multiple entries for a particular template:
```json
[{"template": {"id": 1, "name": "A", "created": "02/02/2016"}},
{"template": {"id": 1, "name": "A", "created": "02/01/2016"}}]
```

If that is what we are after then the plans API may be the more appropriate path to getting this information. Its already returning the template that was used to create the plan and it provides the plan's created date.
```json
{"plan": {"id":123, "name": "Test", "visibility": "unit", "created": "02/02/2016", "owner": {"full_name": "tester", "email": "tester"}, "template": {"name": "A", "active": true, "start_date": "01/31/2016", "review_type": "informal_review"}, "state": "new", "institution": "California Digital Library"}
```
