### ISSUE TITLE
USGS Org not available when creating plan

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#165]
I can set my affiliation in my profile to USGS but it doesn't appear in the Participating Institutions list (related issue #162 ) or for the Org selection on Q2 when I create a new plan. This prevents me from accessing USGS internal templates. 

![screen shot 2018-05-25 at 10 13 07 am](https://user-images.githubusercontent.com/12703638/40557342-a583b5aa-6004-11e8-8cb0-69fe9c2c46b7.png)

**Comment by briri** [comment]
USGS is a funder only on the stage server.
![screen shot 2018-05-30 at 9 50 50 am](https://user-images.githubusercontent.com/1204467/40735084-17a1a398-63ef-11e8-8a4c-bf695f38e8f5.png)

When I update their record to funder+organization they again appear in the research org list on the create plan page.

**Comment by stephaniesimms** [comment]
well that explains that. mysterious how they became a funder only. i'll test and make sure everything is working as expected. thanks for sleuthing.

**Comment by stephaniesimms** [comment]
all better now and serving up all the templates. closing.
