### ISSUE TITLE
indented lists not matching what is in CKEditor

### ISSUE THREAD

**Issue by strasser** [CDLUC3/dmptool#17]
From BB # 117
@mxsstrong:
http://dmp2-dev.cdlib.org:20225/plans/437/details
if i indent in CKEditor, the numbered list shows up as numbers. In the preview they show up as letters 
![2788295670-screen shot 2014-05-06 at 8 37 20 am](https://cloud.githubusercontent.com/assets/418026/3204163/58ff156a-eda5-11e3-8174-2d3addf8a4c5.png)

![3338260502-screen shot 2014-05-06 at 8 37 00 am](https://cloud.githubusercontent.com/assets/418026/3204164/5b7ea59e-eda5-11e3-8dae-f40576eb5bb2.png)

**Comment by mxsstrong** [comment]
problem appears in the subintendation - sub level.  not sure if it's ckeditor or the HTML preview.  Export as RTF is correct and matches what is in CKEditor.  Export as PDF removes any numbering/lettering in sublevels.  So each export (HTML, PDF, RTF) reacts differently.

https://dmp2-dev.cdlib.org/plans/437.pdf


![screen shot 2015-01-05 at 2 49 42 pm](https://cloud.githubusercontent.com/assets/810543/5621420/1e95a1a4-94ea-11e4-8844-fd22b9af5fec.png)

**Comment by stephaniesimms** [comment]
Fixed and deployed by @sfisher. RTF export replaced with DOCX.
