### ISSUE TITLE
Replace welcome email with welcome message

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#170]
Update the system so that it no longer sends out a welcome email to prevent SES email bounces. Replace it with a welcome message that the user will see when they first visit the dashboard page after initial account creation.

**Comment by stephaniesimms** [comment]
welcome email is disabled and the current dashboard message is plenty. but it would be better if you can remove the blue bar and message that says "No records associated" (screenshot below). i don't think these appeared before..?

![screen shot 2018-05-30 at 2 58 30 pm](https://user-images.githubusercontent.com/12703638/40749819-1c5ceab6-641a-11e8-932c-4a14917c8ccd.png)
