### ISSUE TITLE
Org admins not permitted to access Templates menu

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#172]
an Org Admin reported that she wasn't able to access the Templates menu. I tested and confirmed that this is happening on DMPTool prod but not on Roadmap. I can access everything as a Super Admin but Org Admins receive the following error (screenshot) when they select "Templates" from the Admin dropdown menu. Please fix asap @briri -

![screen shot 2018-06-07 at 12 38 39 pm](https://user-images.githubusercontent.com/12703638/41122456-757de1d6-6a50-11e8-9e89-99e1142f17cc.png)

**Comment by briri** [comment]
patched in place on Prod. Pushed fix to development branch: https://github.com/CDLUC3/dmptool/commit/542e6e8473ce5d65efc958866618a96d77e887d7

Roadmap v1.1.0 changed the link that appears behind 'Templates' in the Admin menu based on whether the user is a super or org admin. We neglected to bring that change across to our customized version of the menus.
