### ISSUE TITLE
Fix message when using Shib login w/different language selected

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#176]
Testing on dmptool stage, I get the message below when I select a different language and then log in via Shib. It should tell me I logged in successfully w/my institutional credentials. I'm not sure if this is a missing string or some other issue?

![login-notice-languages-shib](https://user-images.githubusercontent.com/12703638/41680668-21c8eea0-7487-11e8-9969-be300cb39e50.png)

**Comment by briri** [comment]
yeah a missing translation. let me see if its in roadmap

**Comment by stephaniesimms** [comment]
it's missing for both French and Portuguese then. i caught a couple of other tiny missing strings in a new issue https://github.com/CDLUC3/dmptool/issues/179

**Comment by stephaniesimms** [comment]
string is still missing or maybe all of these translation file issues didn't get deployed?

**Comment by briri** [comment]
ah sorry. submitted as a PR to roadmap. will merge in tomorrow.

**Comment by stephaniesimms** [comment]
this is fixed.
