### ISSUE TITLE
Update request feedback email text sent to org contact

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#181]
Now that we changed this functionality we need to update the email text by deleting the first sentence after the salutation. just update it for the DMPTool/US-en for now:

"All the best
The DMPTool
Please do not reply to this email..."

![screen shot 2018-06-20 at 1 33 53 pm](https://user-images.githubusercontent.com/12703638/41683149-b066bcc6-748e-11e8-804c-8afee9f3827f.png)

**Comment by briri** [comment]
Its a shared line in the po file. Part of the signature used across all emails. Will have to wait until a suitable fix is in place on Roadmap.

**Comment by stephaniesimms** [comment]
transferred this issue to roadmap
