### ISSUE TITLE
Cannot upload/update file for institutional logo

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#182]
From Reid Boehm:
I am an administrator for our University of Notre Dame DMPtool account. I
am having trouble trying to upload a new image for our account. I keep
getting a "something went wrong" message. I have tried several sizes,
different images and file formats. Is there anything I am missing to make
this work?

![screen shot 2016-04-12 at 2 04 29 pm](https://cloud.githubusercontent.com/assets/12703638/14475727/3e87491e-00b8-11e6-9a16-cc5e0cdf6b8e.png)

**Comment by stephaniesimms** [comment]
@briri this could be related to the problems we had displaying logos when testing before the migration to AWS

**Comment by briri** [comment]
Yes, this is likely tied to the move to AWS. I'll do some testing and let you know what I find

**Comment by stephaniesimms** [comment]
fix deployed on 4 May 16
