### ISSUE TITLE
Bug with the 1 click plan creation process 

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#187]
I found this bug when trying to utilize the new 1 click plan creation feature from http://dmptool.org/public_templates

Clicking the "Create New Plan" link on a specific funder the user gets a 500 error. 

Clicking the "Copy Link to Create new plan" and then opening this URL the user also gets a 500 error.

**Comment by briri** [comment]
This was a bug in Roadmap, so added a ticket there: https://github.com/DMPRoadmap/roadmap/issues/2580

Patch is in place and will be deployed next Thursday

**Comment by briri** [comment]
@mariapraetzellis this fix has been deployed to stage

**Comment by mariapraetzellis** [comment]
Checked this on stg and it is now working as expected. Thanks @briri!

**Comment by briri** [comment]
Failing for the new Tetiaroa Society Template
