### ISSUE TITLE
"contact us" on dmp.cdlib.org

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#190]
The "Contact Us" page on dmp.cdlib.org <https://dmp.cdlib.org/contact.html> returns the text of the FormMail PHP script when you hit "send":
![dmpcontact](https://cloud.githubusercontent.com/assets/1558172/17113551/184755d8-5260-11e6-805b-79ff819fb963.jpg)

**Comment by mxsstrong** [comment]
Background: we noticed this issue when seeing if the [problem of email not going into Footprints](https://www.pivotaltracker.com/story/show/99830476) was also present using this contact form.  

The email problem appears to be more widespread and not just with DMPTool.  We are seeing it from individuals on the UC3 team using pine email client for nagios acknowledgements as well as some form submissions on the CDL website.

**Comment by stephaniesimms** [comment]
email contact issues resolved by redirecting to cdlib.org Contact form
