### ISSUE TITLE
DMPTool by the Numbers displaying incorrect number for Participating Orgs 

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#191]
I just noticed that the DMPTool by the numbers section on the home page has 408 participating institutions now. Last I looked it was around 270ish. I assume this is b/c of the ROR integration db changes? 

I checked the Participating Institutions list and it looks like some of those listed should not actually be managed accounts, though it is hard to say for sure without seeing the old version. Some examples of orgs I don't think have managed accounts:

Bishop Ascendant Inc. (bishopascendant.com)
Arukah Institute of Healing (arukahinstitute.org)
JoJo Cups

**Comment by briri** [comment]
updated the records in the database. Looks like one of my manual cleanup scripts after the upgrade incorrectly defined them as "managed".
