### ISSUE TITLE
Account creation from Shib for user with non-ASCII characters in name fails

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#196]
The shibboleth handshake appears to be happening without issue and the omniauth callback processes normally. This is a new user though so it attempts to bring them to the new user sign up page which results in:
```shell
F, [2018-07-27T09:19:21.259334 #3333] FATAL -- : 
ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
    122: 
    123:       <!-- main page content rendering -->
    124:       <main class="container">
    125:         <%= yield %>
    126:       </main>
    127: 
    128:       <!-- footer rendering -->
  /appsactivesupport (4.2.10) lib/active_support/core_ext/string/output_safety.rb:185:in `concat'
  /appsactivesupport (4.2.10) lib/active_support/core_ext/string/output_safety.rb:185:in `concat'
  /appsactionview (4.2.10) lib/action_view/buffers.rb:12:in `<<'
  app/views/layouts/application.html.erb:125:in `_app_views_layouts_application_html_erb___2340179509729603470_47323632437720'
  /appsactionview (4.2.10) lib/action_view/template.rb:145:in `block in render'
  /appsactivesupport (4.2.10) lib/active_support/notifications.rb:166:in `instrument'
  /appsactionview (4.2.10) lib/action_view/template.rb:333:in `instrument'
...
  app/controllers/users/omniauth_callbacks_controller.rb:82:in `handle_omniauth'
  app/controllers/users/omniauth_callbacks_controller.rb:9:in `block (2 levels) in 
...
  /appsrailties (4.2.10) lib/rails/engine.rb:518:in `call'
  /appsrailties (4.2.10) lib/rails/application.rb:165:in `call'
  /appsrailties (4.2.10) lib/rails/railtie.rb:194:in `public_send'
  /appsrailties (4.2.10) lib/rails/railtie.rb:194:in `method_missing'
```

I did a quick scan of our DB for others that have non-ASCII characters in their names or emails: `select firstname, surname, email from users where not email REGEXP '^[A-Za-z0-9\.,@&\(\) \-\_]*$' OR not firstname REGEXP '^[A-Za-z0-9\.,@&\(\) \-\_]*$' OR not surname REGEXP '^[A-Za-z0-9\.,@&\(\) \-\_]*$';` 

We have just over 100 users whose names have internationalized characters, but all email addresses are ASCII. I was able to create an account with non-ASCII characters in the name fields but not the email address (HTML5 rules prevent 'email' input type from having them).

Contacted the customer to have them try it on stage where we have placed some debug statements to print out the info that we get from Shib.

**Comment by stephaniesimms** [comment]
removing this from the board until we receive more info from Cornell re users w/non-ascii characters in their names who can't create accounts. waiting for them to test on stage.

**Comment by stephaniesimms** [comment]
still no word from Cornell about whether this issue persists. closing it out for now.
