### ISSUE TITLE
Institutions not populating drop down list on login option 1

### ISSUE THREAD

**Issue by scoutcalvert** [CDLUC3/dmptool#198]
Attempting to login from Michigan State, the drop down list won't populate, so I can't chose my institution and login. Problem is the same with Firefox and Safari.

If this is not the place for this, apologies, just let me know.

![screen shot 2018-08-16 at 9 42 06 am](https://user-images.githubusercontent.com/7155662/44212222-c6c77100-a138-11e8-9e0d-0b772ea7875b.png)

**Comment by briri** [comment]
You should be able to login now @scoutcalvert
