### ISSUE TITLE
Remove vertical bars in banner and fix logo sizing

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#199]
It turns out many institutional logos are too wide to fit nicely into the branding banner as currently designed. Some logos (UCSD) can't be uploaded at all owing to incompatible aspect ratio. In the short term we should remove the two vertical bars separating banner from institution name and contact/URL.

Permanent solution is to redesign the branding banner to accommodate the large horizontal logos.

![screen shot 2018-08-16 at 9 09 08 am](https://user-images.githubusercontent.com/12703638/44220654-12c3e700-a134-11e8-988f-66b5116e2bc7.png)

**Comment by briri** [comment]
Recommendation is to:
- Remove CSS pseudo-elements (they create the vertical bars
- Introduce Flexbox to help align the logo/text/links sections of the header
- Also add Flexbox to help with the layout of the footer and home page sections

Within the core Roadmap project:
- Remove the logic that resizes org logos when uploaded
- Add CSS media queries to properly size and hide/display the logo

**Comment by briri** [comment]
removed vertical bars and restructured header per conversations with the UX team.

The org name is now on the left, the logo in the middle and links to the right (assuming all are present of course)

**Comment by briri** [comment]
Also removed the logic that resizes the logos when uploaded. So far they appear to be a less fuzzy.

Added media queries as well. The branding menu is folded into the hamburger menu when viewed on a phone/tablet. If the user is associated to an org (if its not the 'Non Partner Institution') then the org name appears on the left side of the fixed menu when viewing from a mobile device, otherwise the DMPTool logo appears there

**Comment by stephaniesimms** [comment]
i think it looks good without vertical bars in both the top nav banner and org branding area.

but i think there needs to be some resizing logic (see giant carebear logo screenshot below)
![constrain-logo-size](https://user-images.githubusercontent.com/12703638/45717483-ffe76c80-bb4e-11e8-895f-528da525081b.png)

**Comment by stephaniesimms** [comment]
the logo display size looks good for dmptool org logos in the banner. however, we should also display the uploaded org logo at the constrained size. currently i see a huge care bear on the Org details page (screenshot). please just make it the same size as the banner display @briri 

<img width="1045" alt="screen shot 2018-10-09 at 12 50 19 pm" src="https://user-images.githubusercontent.com/12703638/46694851-bb397900-cbc2-11e8-8830-9f417ef3378a.png">

**Comment by stephaniesimms** [comment]
looks good! i'll create an issue in roadmap repo. closing.
