### ISSUE TITLE
Institutional admin unable to assign roles (redux)

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#200]
I had an issue for this (#196) but thought it actually worked. Now I've confirmed it is broken. Logging in as the institutional admin and clicking on the "institution profile/assign role tab" and searching for a known person by name returns this error:
![dmp01](https://cloud.githubusercontent.com/assets/1558172/19357733/b84652e0-9127-11e6-916d-2c65e420649f.png)

Searching for a known person by email returns this error:
![dmp02](https://cloud.githubusercontent.com/assets/1558172/19357741/c2d7e9ee-9127-11e6-8cde-bf64eef1706f.png)

This should work more like how the DMPTool admin sees it--a list of all users for the institution, and can "edit" the permissions:
![dmp03](https://cloud.githubusercontent.com/assets/1558172/19357788/f738fcdc-9127-11e6-9587-2daeaf98644e.png)

**Comment by stephaniesimms** [comment]
I confirmed that searching by email is broken and always returns the error above. 

Searching by a known person by name (which requires correct spelling of first and last name, with no chance to verify) worked for me, but was not a very user-friendly experience. Likewise, if a user has already been granted admin roles and you attempt to search for them by name, the system returns the not-very-helpful message below:
![screen shot 2016-10-13 at 10 34 23 am](https://cloud.githubusercontent.com/assets/12703638/19359819/a97150c2-9130-11e6-9708-c7aa5d86099e.png)

**Comment by stephaniesimms** [comment]
removed search by email and enhanced search/listing functionality. wiki documentation updated to reflect changes.
