### ISSUE TITLE
institutional_admins method in app/controllers/institutions_controller.rb hard-codes role_id of 5 for Institutional Administrators

### ISSUE THREAD

**Issue by medined** [CDLUC3/dmptool#201]
The test sql provided with the project has an id of 5 for the Institutional Administrator role. However, this constraint should not be placed on all configurations. 

```
def institutional_admins
    @user_ids = Authorization.where(role_id: 5).pluck(:user_id) #All the institutional_admins
    ...
  end
```

**Comment by briri** [comment]
Great catch @medined. Feel free to send a pull request to address this if you have time. Otherwise I'll try to get to it later this week or next week.

**Comment by briri** [comment]
Fixed and will be released tomorrow. Thanks again for pointing it out @medined!
