### ISSUE TITLE
Verify data for multi-select box answer format 

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#205]
We removed multi-select box as an answer format in the roadmap code. 
https://github.com/DMPRoadmap/roadmap/issues/1771

All existing questions w/this format should become multiple choice format instead, which has the same functionality. Check that this worked for the templates that use it and that we have no data validation errors in dmptool. We have 16 templates that use the multi-select box but none of them appear to have any values defined. So unless they have the 'additional info' checkbox ticked then there's actually nowhere for the user to answer the question.

**Comment by briri** [comment]
Looks like any questions that were multi-select have been converted to text for backward compatibility.

<img width="1294" alt="screen shot 2018-12-12 at 1 57 45 pm" src="https://user-images.githubusercontent.com/1204467/49901493-2d724800-fe16-11e8-8812-4c82015eac54.png">

I don't b believe any of the multi-selects were used properly in the past. They all ask the user for one selection in the questions' language:
```
<p>6.6.a Estimate Percentage of Assets Under SD 609 Restrictions<br>In your estimation, what percentage of the digital assets in this DMP fall under SD609 restrictions?</p>

<p>Project Duration<br>Please provide the project duration [months]</p>

<p>Project Duration: Please enter the number of months over which the project work will be funded.</p>
```

It does not however look like the template itself is backward compatible. The old multi-select options are missing:

<img width="1092" alt="screen shot 2018-12-12 at 2 02 48 pm" src="https://user-images.githubusercontent.com/1204467/49901700-b8ebd900-fe16-11e8-8ea8-9d2edc8a479e.png">

**Comment by stephaniesimms** [comment]
what template is this in the screenshot @briri ? to my knowledge only GoMRI and USGS have such long/complex templates...

my feeling is that as long as none are new/published templates it doesn't matter too much how we handle the conversion. this looks fine to me to retain the multi-select text in the additional info field.

**Comment by stephaniesimms** [comment]
answer format converted to text looks good. closing.
