### ISSUE TITLE
Institutions page is broken

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#207]
This page generates an error:
https://dmptool.org/institutions
or clicking on "Institution Profile"
![dmptool](https://cloud.githubusercontent.com/assets/1558172/25972071/64d54194-3653-11e7-9b2a-aee58bacf3fc.png)

**Comment by briri** [comment]
Thanks Perry. I’ll look into it.

**Comment by briri** [comment]
This has been resolved Perry.

I recorded the issue in Github: https://github.com/CDLUC3/dmptool/issues/208

Thank you again for reporting it!
   Brian
