### ISSUE TITLE
usage stats question

### ISSUE THREAD

**Issue by elliewix** [CDLUC3/dmptool#209]
I'm reviewing the usage statistics for UIUC and have a question about what I'm seeing.  

When I got into the statistics for any particular month in the dropdown, the language of the results page uses the name of the previous month.  E.g. 2017-Jan is reporting "4 new users for December".

Given that I have an option for 2017-May, should I interpret this as "2017-Jan" being a final report of 2016-Dec?

<img width="484" alt="screen shot 2017-05-16 at 10 58 24 am" src="https://cloud.githubusercontent.com/assets/4133077/26115784/aac1af22-3a26-11e7-9398-db0d62757bc9.png">

**Comment by stephaniesimms** [comment]
Hi! Yes, the stats are generated automatically at the end of each month but appear in the dropdown on the first of the new month. So 2017-Jan is the final report for 2016-Dec as you noted above.

We realize this isn't ideal but wanted to get something out to collect feedback and design a more robust dashboard in the new system. Please let me know if you have any suggestions and/or comments about what stats are most useful to you.
