### ISSUE TITLE
New accounts created via Shib with duplicate emails fail

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#209]
UCR just setup their shibboleth system and DMPTool is having trouble linking their accounts when they attempt to login via Shib. Their IdP returns the user's email as `user.name@ucr.edu;user.name@ucr.edu`. 

The code does not appear to be stripping off this duplicated email address. 
![dmptool-error-01](https://user-images.githubusercontent.com/1204467/46700802-ab299580-cbd2-11e8-8bbc-4d21557ad7b7.PNG)
![dmptool-error-02](https://user-images.githubusercontent.com/1204467/46700803-ab299580-cbd2-11e8-8dc9-e7d42866d643.png)

**Comment by cpwillett** [comment]
Additional info from Katherine Koziar:
---
More information: I asked a couple of users who also had previous email accounts to sign in. It created a second account for them when they signed in, instead of linking accounts.
 
-k

**Comment by stephaniesimms** [comment]
reported that this is working as expected for UCR shib users now. closing issue.
