### ISSUE TITLE
Several Default Resource Links Need Updating

### ISSUE THREAD

**Issue by cmalinowski3** [CDLUC3/dmptool#210]
We went through each of the available templates and found several links for the default resources that are either broken or out of date. Below is a summary of the broken links and proposed updates. See the attached spreadsheet for the full list: [DMPTool_BrokenResources.xlsx](https://github.com/CDLUC3/dmptool/files/1019226/DMPTool_BrokenResources.xlsx)

**Comment by stephaniesimms** [comment]
many, many thanks, @cmalinowski3! we're aware of the DOT links and working w/them directly to maintain their template. i'll tend to the rest asap.

**Comment by cmalinowski3** [comment]
Thank you for the quick reply and action! Much appreciated!
- Chris Malinowski on behalf of Data Management Services, MIT Libraries

**Comment by stephaniesimms** [comment]
links updated. closing this issue.
