### ISSUE TITLE
redirect URL to YouTube video

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#210]
We used to have a promotional video at https://dmptool.org/video
The video is now available on YouTube at https://youtu.be/xT1by-p5jUw
Could the URL https://dmptool.org/video redirect to the copy on YouTube?

**Comment by marisastrong** [comment]
Here is a link that is under the CDLUC3 YouTube Channel 
https://youtu.be/SysOS3NZk1o

**Comment by briri** [comment]
Thanks @marisastrong. I updated the [Pivotal ticket ](https://www.pivotaltracker.com/story/show/160903249)that we used to track the necessary changes for the public_plans redirect. 
@jimvanderveen if you could give it a try on dev and stage that would be great. Thanks!

**Comment by briri** [comment]
related to: https://www.pivotaltracker.com/story/show/160903249

**Comment by jimvanderveen** [comment]
I've got https://dmptool-stg.cdlib.org/video set up to redirect. Please let me know if this is not working the way you expect, e.g. address bar retaining our URL.

**Comment by jimvanderveen** [comment]
@stephaniesimms took a look at this, approves. We agreed *not* to roll this out on production late on Friday, so I'll do that on Monday.

**Comment by jimvanderveen** [comment]
This change is ready to push to production on the puppetmaster whenever you're ready, @briri

**Comment by briri** [comment]
Thanks @jimvanderveen will coordinate with you this afternoon

**Comment by stephaniesimms** [comment]
just triple checked and redirect is working nicely. closing.
