### ISSUE TITLE
Modifications to Grant number/URL and ID fields

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#213]
The fields GrantID and ID within the Project Details page are redundant as currently defined in the tool tips. 

I propose we change ID to "Grant ID or Number" and change Grant number/url to "Grant URL". This way we will have a field for NSF grant URLs, which we have a lot of, and a separate field to record the crossref grant ID.

**Comment by briri** [comment]
The grant ID field is used for both purposes. I will hide the separate identifier field
