### ISSUE TITLE
Rails 5 UAT issues

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#214]
Listing out all issues identified while doing Rails 5 testing on dmptool-stg

- [x] The ID field is already filled out when creating a new plan. Not sure where these numbers are coming from
- [x] - Show password checkbox doesn't work (noticed when creating a new account)
- [x] - Error message listed in Privileges column for user: "Project-Id-Version: app 1.0 Report-Msgid-Bugs-To: contact@translation.io POT-Creation-Date: 2020-09-15 15:51+0000 PO-Revision-Date: 2020-09-15 17:51+0200 Last-Translator: FULL NAME <EMAIL@ADDRESS> Language-Team: English Language: en_US MIME-Version: 1.0 Content-Type: text/plain; charset=UTF-8 Content-Transfer-Encoding: 8bit Plural-Forms: nplurals=2; plural=n != 1;"
 ![screenshot-dmptool-stg cdlib org-2020 10 02-09_34_50](https://user-images.githubusercontent.com/27511575/94947567-b0084380-0492-11eb-80d5-491ebb812c89.png)
- [x]  - Requesting feedback on a plan does not send an email notification. Trying to request feedback on this plan: https://dmptool-stg.cdlib.org/plans/54857/request_feedback
- [x] - When requesting feedback and sharing a plan, the link in the email goes to a 500 error (http://uc3-dmpx2-stg-2a/plans/54857)
- [x] - Tinymce textarea editors for chrome are not loading 
- [x] Unable to change affiliation when logged in as a super admin. I tried logging in/out a few times and got the same message: 
![screenshot-dmptool-stg cdlib org-2020 10 04-09_30_50](https://user-images.githubusercontent.com/27511575/95021216-79623280-0624-11eb-9033-5d7d3c1164a8.png)
- [x] I'm not sure if this is a bug or just b/c it is staging. When trying to connect my ORCID to my DMPTool profile I get the following message from ORCID: "Redirect URI doesn't match your registered redirect URIs." 
- [x] When updating my profile and trying to change the Organization field I get an error message: " Error: Unable to update the profile. Language must exist". The language set for my profile is "English": https://dmptool-stg.cdlib.org/super_admin/users/38764
- [ ] Adding a Collaborator to a plan goes to a 500: When clicking Submit from [this plan](https://dmptool-stg.cdlib.org/plans/54794/contributors) you are directed to: https://dmptool-stg.cdlib.org/roles. I did receive the email though. 
- [ ] Finalize/Publish tab goes to a 500 https://dmptool-stg.cdlib.org/plans/54794/publish
- [x] Editing a template by re-ordering questions gives a 500 (https://dmptool-stg.cdlib.org/org_admin/templates/470/phases/456/sections/3382/questions/4314)
- [x] "Error" message displayed when selecting the option on a template that should have triggered a notification. https://dmptool-stg.cdlib.org/plans/54861/edit?phase_id=1267
![screenshot-dmptool-stg cdlib org-2020 10 04-18_07_53](https://user-images.githubusercontent.com/27511575/95031825-deda1180-066c-11eb-9b3f-ff048297712a.png)
- [x] Merging two accounts gets a 500 after clicking on Merge 
- [x] Unable to enable the feature to request feedback for an org. When I tried to save the request feedback feature as On I get the following error message: " Error: Unable to save the organization. Feedback email subject can't be blank". This was on this org: https://dmptool-stg.cdlib.org/org/admin/139/admin_edit#feedback
- [x] Unable to set plan visibility (to either organization or public). When I select the radio button and navigate away from the tab and then return the setting is back to Private. Doing this on plan: https://dmptool-stg.cdlib.org/plans/54864/edit?phase_id=762
- [ ] I'm not sure if this is just a test environment thing, but the email sent when a notification is triggered or a user requests feedback on a plan needs to be updated. It currently reads: "Please do not reply to this email. If you have any questions or need help, please contact us at uc3@ucop.edu or visit https://example.org/contact". It should be "https://dmptool.org/contact-us"
- [ ] Noticed that the  ID field is back on the Project Details page. Not sure if this is just a stg thing, but wanted to be sure it's not going into prod. 
- [x] Clicking on the Request Feedback tab directs to a 500 (https://dmptool-stg.cdlib.org/plans/54867/request_feedback)
- [ ] The link under a user profile for how to use the API needs to be updated to point to https://github.com/DMPRoadmap/roadmap/wiki/API-V0-Documentation

**Comment by briri** [comment]
the ID that gets placed in there is the unqiue id of the record in the DB. It corresponds to the one you see in the URL. We can comment out this behavior for DMPTool if you'd like

**Comment by briri** [comment]
The affiliation change issue stemmed from the fact that some of the Orgs that have been auto-created by the new RORified Org selector were created with a blank language_id. The new Rails 5 code sets this value to the default language if none is specified so it should not be an issue going forward.

I am adding an upgrade script that will fix any of these records when we release Rails5. I have run it already on stage so you should now be able to change your affiliation.'

The same scenario was causing the issue when enabling feedback. I added as script to default those as well.

**Comment by briri** [comment]
The ORCID issue was a configuration error. It is now connected with the ORCID sandbox (from the stage server)

**Comment by briri** [comment]
I'm not able to replicate the "Editing a template by re-ordering questions gives a 500" issue @mariapraetzellis. If there are 2 questions numbered 1 and 2 and I try to update 2 to be 1, I get an error message that the number must be unique. Is that what you mean? 

I could also not replicate ""Error" message displayed when selecting the option on a template that should have triggered a notification." I added a conditional to the UCOP template (2nd question in 1st section is triggered when you select 'Maybe') and it sent the email.

**Comment by mariapraetzellis** [comment]
Confirmed that I am able to add a contributor to a plan successfully. 

I also successfully re-ordered questions on a template.

**Comment by briri** [comment]
I think all of these issues have been resolved
