### ISSUE TITLE
Review Create Account/Sign In workflow

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#214]
Roadmap Milestone: https://github.com/DMPRoadmap/roadmap/milestone/27
UX wireframes (to revisit): http://h90c3m.axshare.com/#g=1&p=home

Roadmap create account/sign in should follow DMPonline workflow. We want to implement something optimized/customized for DMPTool where a majority of users employ Shib. Recover account functionality is no longer required for MVP, but something we could keep in mind for the future.

**Comment by JEK-III** [comment]
Wireframes have been updated to
1. remove the "login with ORCiD" button
2. add "Institution not on list? **Create an account with any email address**"  option
3. change the term "partner" to "participating"

Institutional login is still wired up as a modal, but a separate-page version is here:
https://h90c3m.axshare.com/#g=1&p=select_partner_institution
