### ISSUE TITLE
Allow for multiple output descriptions

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#216]
Add a new Dataset tab similar to the one introduced by [DMPOPIDOR](https://github.com/OPIDoR/DMPOPIDoR/tree/dmpopidor-master). The user can then define datasets based on the expected info from the [RDA common metadata standard](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/blob/master/examples/JSON/JSON-schema/1.0/maDMP-schema-1.0.json).

The narrative portion of the DMP will remain unchanged at this point in time.

Each plan can have n datasets.

**Comment by mariapraetzellis** [comment]
Fields to include for each output: 

- Description
- Format
- Anticipated Volume
- Release Timeline (Tooltip: "How long after acquisition will this data be available" 
- Intended Repository 
- License for Reuse


I like how this application offers a description of the selected value for License and Repository: 

![screenshot-ezdmp org-2020 10 09-11_03_28](https://user-images.githubusercontent.com/27511575/95616785-41d9f880-0a1f-11eb-8e2b-e92bb41bbae1.png)
