### ISSUE TITLE
Broken link to image in Incommon metadata in dmp.cdlib.org

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#217]
There's a broken link in the Incommon metadata to the DMPTool logo. This is used by identity providers. I think we recently changed something about dmp.cdlib.org that caused this. See the mdui:Logo element in the Incommon-metadata.xml snippet below.
 
---
`<SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol">
    <Extensions>
    [...]
      <mdui:UIInfo>
        <mdui:DisplayName xml:lang="en">DMP Tool</mdui:DisplayName>
    [...]
        <mdui:Logo height="53" width="153" xml:lang="en">https://dmp.cdlib.org/img/dmptool_logo.svg</mdui:Logo>
     </mdui:UIInfo>`

**Comment by briri** [comment]
Thanks @cpwillett. This has been broken since we removed the old brochure site. I setup that directory on the dmptool site and copied the logo over so it should no longer be broken.

**Comment by cpwillett** [comment]
Thanks Brian!

**Comment by mxsstrong** [comment]
oh i can easily update the Incommon metadata to match a valid directory  - especially since we're not carrying over the dmpbrochure to the new server.
