### ISSUE TITLE
Info notifications used to have a light blue background but are now green

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#220]
Update system notification messages so that they have the old light blue background color.

**Comment by stephaniesimms** [comment]
colors are still amiss @briri - not sure what they all used to be but currently:
- Info is green with black text (should be light blue)
- Warning is red/orange with black text (should be swapped with Danger colors?)
- Danger is salmon/pink with white text (should be swapped with Warning colors?)

<img width="938" alt="screen shot 2018-11-27 at 9 35 17 am" src="https://user-images.githubusercontent.com/12703638/49100029-cbb3ba80-f227-11e8-9494-ac130bd94fc1.png">

<img width="939" alt="screen shot 2018-11-27 at 9 35 01 am" src="https://user-images.githubusercontent.com/12703638/49100039-cfdfd800-f227-11e8-85ac-dfdd1e0dc6f7.png">

<img width="936" alt="screen shot 2018-11-27 at 9 34 37 am" src="https://user-images.githubusercontent.com/12703638/49100053-d4a48c00-f227-11e8-9f21-ecf9831484c4.png">

**Comment by stephaniesimms** [comment]
tested on prod and notification messages display correct colors. closing.
