### ISSUE TITLE
Resource links should open in a new tab

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#223]
Since the latest release resource links on the public DMPs page open in the same tab. All links should open in a new tab. They appear to be working as expected elsewhere in the tool.

**Comment by briri** [comment]
I can't replicate this issue. The PDFs all open in a new tab on Safari, Firefox and Chrome for me.

Do you have a specific one that's not working?

**Comment by stephaniesimms** [comment]
after checking again they appear to be working fine now. closing issue.
