### ISSUE TITLE
Usage statistics download issue

### ISSUE THREAD

**Issue by wdahdul** [CDLUC3/dmptool#228]
On the Usage Statistics page, clicking the "Download all" button for "No. plans by template" doesn't download a file. In Chrome, an error page pops up: "dmptool.org is currently unable to handle this request.
HTTP ERROR 500". 
The other download buttons work as expected.

**Comment by wdahdul** [comment]
Clicking "Download Monthly Usage" button at the top of the page also results in the same error.

**Comment by briri** [comment]
Related to https://github.com/DMPRoadmap/roadmap/pull/2866

Fix for this will be released this Thursday. Apologies for the delay @wdahdul
