### ISSUE TITLE
Section +/- appear too close to the right of the section title

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#232]
The +/- font awesome icons appear to the right of the section titles. Move them back to the left hand side and make sure there is enough padding between.

<img width="501" alt="screen shot 2018-11-21 at 8 18 50 am" src="https://user-images.githubusercontent.com/1204467/48854239-3ff0e880-ed66-11e8-8cdc-d2e6af0b74b2.png">

**Comment by stephaniesimms** [comment]
section titles are styled correctly now. creating a separate issue for guidance. closing.
