### ISSUE TITLE
Fix issues with Contact Us page

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#234]
I noticed the following issues on the contact form page and when submitting the form:
- Incorrect link in text above the form - it goes to roadmap github. Should be a link to CDL website https://www.cdlib.org/
- Adjust layout of text by moving the second sentence to the first line and remove extra space at end of hyperlink (screenshot below).
- I submitted the contact form multiple times on prod and stage to compare. On stage it generates 2 emails in Freshdesk (should only generate 1). On prod the Recaptcha is missing, however, so this could be related?

![screen shot 2018-11-28 at 11 20 49 am](https://user-images.githubusercontent.com/12703638/49176451-b4480080-f2ff-11e8-9677-027f9efb9bb2.png)

**Comment by briri** [comment]
It looks like its only sending out one email now based on the logs. Can you please confirm @stephaniesimms? The subject of my test email is "Test contact"

**Comment by stephaniesimms** [comment]
just one email came through to Freshdesk. closing.
