### ISSUE TITLE
Tab reconfiguration

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#236]
- [x] Remove the 'Overview' tab
- [x] Move the 'Template name/version' info from the Overview tab to the Write Plan tab
- [x] Move the Sharing form into the Conributors tab and rename it to 'Collaborators'
- [x] Rename the Download tab to Finalize/Publish

**Comment by mariapraetzellis** [comment]
Note to @mariapraetzellis that I need to update user documentation & make a post informing folks about this change.

The new tabs are in staging now so can use this for screenshots.
