### ISSUE TITLE
Restrict DOI minting and ResearchOutput functionality

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#239]
Add a column to the template table that enables/disables the DOI minting functionality and Research Outputs tab

**Comment by briri** [comment]
DOI minting will be a flag on the Org record and only available to Org admins (for now).
Research Outputs tab will be triggered by a flag on the Template record (for now, eventually open to all).

**Comment by mariapraetzellis** [comment]
Need to verify that non TS users do not see the Research Outputs tab or the DOI minting. Can log in as any org but need to check the TS as the funder template.

**Comment by mariapraetzellis** [comment]
Confirming that the ID minting feature & Research Outputs tab are not available to regular admin or regular users.
