### ISSUE TITLE
Org admin unable to create a new question

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#239]
The Univ. of Hong Kong reported that they could not add questions to templates. After investigation it was discovered that the following error was occurring:
  `question.annotations cannot be blank`

Updated the plans controller logic to set this value to an empty array.

**Comment by stephaniesimms** [comment]
this is working as expected on dmptool-stg. just wanted to confirm that the missing red asterisks for required fields and other things related to the latest roadmap code won't get deployed w/this branch @briri ? closing this one anyway.
