### ISSUE TITLE
Verify DOI minting functionality

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#240]
Verify that the DMPTool is still able to communicate with the DMPHub and receives a DOI from the DMPHub

**Comment by mariapraetzellis** [comment]
I need to verify the DOI is generated- only available to admin of TS- and the hub shows a landing page

**Comment by mariapraetzellis** [comment]
Tried to get an ID for this [DMP](https://dmptool-stg.cdlib.org/plans/58892/publish) (and got the following message: "Something went wrong and we were unable to aquire a DMP ID for your plan. Please try again. If the problem persists please contact the help desk at uc3@ucop.edu" 

(Also need to fix the typo on acquire)

**Comment by briri** [comment]
Was an issue on the DMPHub side when saving the 'Funded affiliation'. It is now fixed on dmphub-stg and part of [v0.3.2](https://github.com/CDLUC3/dmphub/releases/tag/v0.3.2)
