### ISSUE TITLE
Admin Plans page throws an error

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#242]
As a super admin and org admin I get the error below when I try to navigate to the Plans page in the Admin menu

<img width="1023" alt="screen shot 2018-12-14 at 8 27 31 am" src="https://user-images.githubusercontent.com/12703638/50014974-3b40de00-ff7a-11e8-92a8-2f437a3635de.png">

**Comment by briri** [comment]
interesting. It loads for me. which org are you associated with?

**Comment by stephaniesimms** [comment]
now just getting the error as a Super Admin. affiliated w/UCSD...
