### ISSUE TITLE
Invitation links to collaborators result in error

### ISSUE THREAD

**Issue by duncdrum** [CDLUC3/dmptool#245]
To reproduce, 
1) create a private plan on the site while logged in with email `A`
2) invite yourself with email `B` as a collaborator

3) On email account `B` follow link to register and see shared plan
Result:
![screen shot 2019-01-17 at 19 36 29](https://user-images.githubusercontent.com/6205362/51352757-d879bf80-1aae-11e9-92d3-3cc858a90484.png)

Expected Result:
the invited person is logged in and can see the plan. 

Tried with current versions of safari, chrome and firefox. Also after clearing the browser cache via shift reload, no joy.

**Comment by briri** [comment]
Thanks for bringing this to our attention @duncdrum. Will add it to the queue for the next release/update.

**Comment by briri** [comment]
This appears to be working now with the latest release  @duncdrum. Thanks again for bringing it to our attention!
