### ISSUE TITLE
Change the default download for customized templates

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#245]
This is a user request. When a user downloads a completed DMP from a customized version of the DCC template, the box that reads: "supplementary section not requested by funding orgs" should default to be checked. 

I think this makes sense to implement, as if the org has added additional questions to their customized template these questions should appear in the downloaded version. 

I realize this is explanation may be confusing, so I can walk you though it to demonstrate.

**Comment by briri** [comment]
This has been updated. You can test by changing your Org to UCOP and then creating a plan using the DCC default template (which UCOP has customized)
<img width="777" alt="Screen Shot 2021-02-10 at 2 13 28 PM" src="https://user-images.githubusercontent.com/1204467/107579655-4f101b00-6baa-11eb-9b54-806618359d01.png">
