### ISSUE TITLE
DMPTool image for IdPs missing

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#249]
Some IdPs display the DMPTool logo; it's a broken link now. It looks like the link is URL encoded in the HTML:
https&amp;#x3a;&#x2f;&amp;#x2f;dmptool.org&amp;#x2f;images&amp;#x2f;DMPTool_logo_blue_shades_v1b3b.svg

See attached png for a screen shot. This is a repeat of issue 126 from a few years ago--seems to have reappeared with the latest upgrade.

![dmptool-idp](https://user-images.githubusercontent.com/1558172/52307351-3b90a080-294f-11e9-8410-a99ce9878900.png)

**Comment by marisastrong** [comment]
what are the steps needed to recreate the problem?  Is this when  a user logs in?  or when using the printenv tool?

**Comment by cpwillett** [comment]
Seems to work now. Anyone can see it, not just people at these institutions. When you go to sign in, click on Your Institution, type in "Texas", choose University of North Texas and click Go. You'll go to the UNT IdP and can see the logo (now). Not all IdPs include the logo, so you have to hunt around. Looking back at the previous ticket, it looks like UNT, University of Texas at Dallas, and Woods Hole (WHOI) are three that do, so they're good to test with. Thanks for fixing it!
