### ISSUE TITLE
Merge orgs feature hits a 500

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#252]
When trying to merge two organizations, I hit a 500 error after hitting the final "Submit" button. I am able to select the org to merge, the analyze step seems to be working fine, and it is only at the last step that I get a 500 error. 

This is only affecting me so not a super high priority to fix.

**Comment by briri** [comment]
Hey @mariapraetzellis I can not replicate this so I think its due to the specific data associated with the Orgs you were trying to merge. Do you recall which ones?

**Comment by mariapraetzellis** [comment]
Seems like this might have been specific to data associated w/ the org I was trying to merge (and can't remember which one!). Will reopen if necessary.
