### ISSUE TITLE
Authorized 3rd Party list

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#261]
We discussed making a list of available 3rd party authorizations and having all possibilities display w/ logos to promote the integrations. This would include RSpace, RAMS & protocols (once we get that one done).  Just adding this ticket so we don't forget, we still need to discuss implementation details.

**Comment by briri** [comment]
<img width="1177" alt="Screen Shot 2021-05-21 at 2 25 59 PM" src="https://user-images.githubusercontent.com/1204467/119199810-94ad7100-ba40-11eb-8216-b2c4521eece1.png">
