### ISSUE TITLE
DMPTool website redesign

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#274]
This is an epic to track the minor redesign of the DMPTool website. We'll be working on the homepage, global navigation, sign-in box, and public plans page in this redesign.

**Comment by rhu001** [comment]
Public Plans page wireframe: https://qvr42y.axshare.com/#id=au4s6r&p=explore__public_dmps_cards_scroll-box_find-plan&view=default&c=1
