### ISSUE TITLE
Mis-labeled Link Label for Hover link "Submit" under My DMPs

### ISSUE THREAD

**Issue by shlake** [CDLUC3/dmptool#28]
From My DMPs list:

When hovering over a DMP, the link "submit" actually goes to the "DMP Preview" page. I think this is mis-labeled and should be "preview".

Submit means something else - if review is turned on.

![screen shot 2014-06-10 at 11 00 48 am](https://cloud.githubusercontent.com/assets/3809325/3231971/0ca94a60-f0b0-11e3-8cbe-c7c96c414cb1.png)

**Comment by mxsstrong** [comment]
should always allow Preview, i.e have no logic behind button. From preview page, user can submit if allowed.  being worked on.
