### ISSUE TITLE
DMP JSON has no 'contact' after the owner removes the plan in the UI

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#284]
The RDA common standard requires a `contact`. We use the owner (or co-owner if the owner is not available) for this information. 

In a scenario where the plan has been "registered" and received a DMP ID and the owner then "removes" the plan via the "My Dashboard" page, the `roles.active` flag is set to false. The JSON checks this flag when gathering the contact info.

See [an example here](https://dmptool.org/plans/67898/export?utf8=%E2%9C%93&format=json&export%5Bform%5D=true&phase_id=400&export%5Bproject_details%5D=true&export%5Bquestion_headings%5D=true&export%5Bunanswered_questions%5D=true&export%5Bformatting%5D%5Bfont_face%5D=Arial%2C+Helvetica%2C+Sans-Serif&export%5Bformatting%5D%5Bfont_size%5D=10&export%5Bformatting%5D%5Bmargin%5D%5Btop%5D=25&export%5Bformatting%5D%5Bmargin%5D%5Bbottom%5D=25&export%5Bformatting%5D%5Bmargin%5D%5Bleft%5D=25&export%5Bformatting%5D%5Bmargin%5D%5Bright%5D=25&button=)

The issue is that the system is then unable to update the DMP ID record in the DMPHub because it is trying to send JSON with no contact.

Should we ignore the `roles.active` flag for these situations or should we consider the plan to be a test and remove it from the DMPHub and EZID?

**Comment by mariapraetzellis** [comment]
We are holding off on this right now as we finalize plans re DMP versioning.
