### ISSUE TITLE
Site redesign

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#285]
Please record any issues with the site redesign on dmptool-stg. Place screenshots in the comments below when possible to help highlight the issue.

If something is complicated or involved (e.g. takes multiple steps to recreate) please open a separate ticket and reference this one in it. You can also use the orange "Feedback" widget on the dmptool-stg page to grab screenshots and add commentary if its helpful.

### Header issues

- [x] User profile menu should be closer to the language menu
- [x] Org logo / name block needs to have a `max_width` defined (see screenshot below of an example with a long Org name)
- [x] Success/error messages not aligned with other content. Also add margin space between them and the header (see screenshot below)

### Footer issues

- [ ] 

### Main content issues

- [x] Sign in / Create account block's height changes when you toggle between the tabs. This causes the height of the underlying image to change. 
- [x] The last part of the Shibboleth (Institutional) sign in is not working.

**Comment by briri** [comment]
<img width="604" alt="Screen Shot 2021-07-29 at 7 42 59 AM" src="https://user-images.githubusercontent.com/1204467/127512584-44536ad8-d78c-40f9-9e3b-646b35cf40e0.png">

Need to align success/error messages with other content and add some margin space between it and the header.

**Comment by briri** [comment]
<img width="1358" alt="Screen Shot 2021-07-29 at 7 46 06 AM" src="https://user-images.githubusercontent.com/1204467/127513200-4eccfdb3-0a60-4581-853e-fbddae19e98b.png">

Need to define a max_width for the organization logo/name section!

**Comment by rhu001** [comment]
Homepage and Header Adjustments: https://docs.google.com/document/d/1cSkb6a_HWZvfFvgwyrEbZpzgsad3_pOcPWDRUaVEZfk/edit?usp=sharing 

Mockup of adjusted homepage: https://qvr42y.axshare.com/#id=ixwqyy&p=home_hero-area_latest-news_right&g=1 

Hi @briri we'll review this document with you on 8/9/21 meeting.

**Comment by mariapraetzellis** [comment]
An annotated version of the homepage design that shows the order of the areas of the page for screen readers, mobile screens, etc. is here: https://qvr42y.axshare.com/#id=tgdtad&p=home_hero-area_latest-news_right_structure&c=1

The photos for the homepage rotating image is here:  https://drive.google.com/file/d/1NNKus_FGPiZAbdRMUN4V7r7GWOtjiT-9/view?usp=sharing

And here’s the folder with high-resolution files: https://drive.google.com/drive/folders/1dhm7baaKZmv-GdQ8uKZ4xzrKsjAbG0oY?usp=sharing

I think we should utilize all photos, except image G
