### ISSUE TITLE
API V2 contributor issue

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#290]
There is a bug in API V2 logic that is fetching old contributor info when a new DMP is created (via the API). 

Each plan has its own contributors so it should just take whatever was sent in the JSON. 

For example: https://dmptool-stg.cdlib.org/plans/59119/contributors

The 'Tom W.' contributor name was pulled from an old record instead of using the 'Maria P.' name that was passed in.

**Comment by mariapraetzellis** [comment]
This is fixed in DMPTool and there is a PR for DMProadmap so closing this issue.
