### ISSUE TITLE
New FAIR Island create plan workflow

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#299]
The current DMPTool plan creation workflow is geared towards researchers who are preparing a grant proposal. The FAIR Island workflows differ.
There are 2 main scenarios:
1. The researcher fills out an application to perform research on Tetiaroa via the UCNRS RAMS system. We are finalizing the integration for this one.
2. The researcher will be performing research on data derived from prior research projects that took place on Tetiaroa. 

For this 2nd scenario, we need to be able to provide a way for these researchers to fill out a DMP.

To work around this gap in the DMPTool's workflows, we can create a new page for the Tetiaroa admin(s) that allow them to:
  - select one of their published templates
  - enter a user's email address
  - click a button that: creates a DMP for that user; invites them to the DMPTool if they are a new user or sends them an email about the new DMP that includes instructions (similar to the one we are using for RAMS)

**Comment by mariapraetzellis** [comment]
I think this workflow is great and useful for other nonstandard (funder) use cases that need to get around the current funder-centered workflow.

**Comment by mariapraetzellis** [comment]
The ability to enable this feature should live in the Template actions list, titled "Email template"

**Comment by mariapraetzellis** [comment]
A few details we discussed:
- The title of the plan should default to {Template name} DMP
- The signature block should be:
```
Thank you, 
The %{org_name} DMPTool team

Please do not reply to this email. If you have any questions or need help, please contact us at %{org_admin_email}
```
- If it's not too time-consuming, add a preview window so users can preview the email text. Apply this feature to the API & feedback request emails as well.

**Comment by mariapraetzellis** [comment]
This is in production and working as expected. I think we can close this issue @briri
