### ISSUE TITLE
Plans table displays the same plan multiple times

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#304]
Both of the plans that we ingested from RAMS into the DMPTool (AeLIMIN+... and AegyptEND...) display multiple times on the plans table.
All of the links appear to point to the same actual plan. This occurs when the user searches for Tetiaroa on the plans table; however, this is not a problem if you search under the plan owner's name. 
![Screen Shot 2021-10-15 at 10 17 57 AM](https://user-images.githubusercontent.com/27511575/137522800-759752e6-3b85-4533-86f3-7479f86443fa.png)

**Comment by briri** [comment]
Patched by adding `distinct` to the search results. This was happening in this scenario due to a join on the contributors table

**Comment by mariapraetzellis** [comment]
This looks good on stg now.

**Comment by briri** [comment]
fixed and deployed in early Dec.
