### ISSUE TITLE
Require a URL in the Related Identifiers text box

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#311]
We recently had an issue with users putting citation information into the Related Identifiers field on the Project Details tab. To avoid this confusion, we should only accept URLs as valid text in this field.

**Comment by briri** [comment]
Also need to heck the logic behind the links displayed in citations. If its not a DOI its displaying the link to the plan itself instead of the external URL

**Comment by briri** [comment]
fixed and deployed in early Dec.
