### ISSUE TITLE
Download plans button directs to a 406 error 

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#312]
A user reported that when clicking on the download button on the Plans page (as an admin user) she is directed to an error. 
![0_Hx7QHL0Ah5dL2s2sIKtNwwsenpZBTvAg](https://user-images.githubusercontent.com/27511575/141866780-4fce7e32-affc-4d0b-bdda-15747f9263e4.png)

![C2Sdu4Go-n0UVNBojJCrtNxYjCdh6yhxRA (1)](https://user-images.githubusercontent.com/27511575/141866941-88701146-bef1-4ea1-a7b2-8f6f35b1a780.png)

**Comment by briri** [comment]
There also seems to be an error when exporting as txt:

undefined method `many?' for #

Backtrace:["/apps/dmp/apps/dmptool/app/views/shared/export/_plan_txt.erb:4:in 


And on certain plans:

undefined method `text' for nil:NilClass

Backtrace:["/apps/dmp/apps/dmptool/releases/20211027171340/app/views/shared/export/_plan.erb:81:in

**Comment by mariapraetzellis** [comment]
I tried downloading the plans table (as a UCOP org admin) and got a 406 in stage. The URL points to https://dmptool-stg.cdlib.org/org_admin/download_plans.csv. @briri

**Comment by briri** [comment]
fixed and deployed in early Dec.
