### ISSUE TITLE
Modifications to new Public Plans page

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#321]
Using this issue to record any bugs in the new Public Plans page

- [x] Remove the following text from the intro blurb: 
> Plans labeled Funded are associated with grants that have been reported as funded through our machine-actionable DMP project. Many plans associated with successfully funded grants do not have the label.
- [x] "View All" link is not working
- [x] The Search feature is not working as expected. For example, a search for "NIH" only gets 3 results, when there are at least 12 plans with NIH as the funder. 
- [x] This is probably just a dev thing, but I noticed many DMPs with a creator listed as "DMP dmpcurator". I think this is just appearing for UCOP plans
- [x] You can select more than one filter value, but it removes the other options so quickly this doesn't really work. We should discuss how we want this to work.
- [x] Also possibly a dev-specific thing, but the DMP ID URLs do not resolve to the DMP ID landing page.  **This is a dev specific thing. The data was originally from the prod server and but the dev DMPHub data is not so the DOIs don't exist**

**Comment by briri** [comment]
Search should use existing `Plan.search` function

**Comment by mariapraetzellis** [comment]
The list of plans to be marked as featured is [here](https://docs.google.com/spreadsheets/d/1nn9Ij0ZzlPLfWnRreJSTmGLKwktYEVrSTTZVwjzPQ_c/edit#gid=0). The mapping of funder template to the corresponding Field of Science is [here](https://docs.google.com/spreadsheets/d/161-xUgX19meXkVzrdA4IEMyZasLCqXnEmU6NK3pK3xI/edit#gid=1667925479)
