### ISSUE TITLE
v3.4.0 issues

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#323]
- [x] - [x] Limit funder list on the create plan page to only allow funders with a published template
- [x] - [x] Unable to click the 'Create' button on the create plan page if user enters a custom research org name
- [x] - [x] Also unable to click the 'Create' button on the create plan page if user selects No research org/No funder checkboxes
- [ ] API V2 still not allowing user login on stage (this was an issue on stage but not prod or dev)
- [x] - [x] Change spelling to "organization" under the checkbox for "I cannot find my research **organisation** in the list" on the Create new plan page
- [x] - [x] When I am in Create Plan mode and select National Institutes of Health (NIH) it then directs me to select which DMP template I would like. This list includes all of the templates twice. 
- [x] - [x] Change spelling of the Finalise/ Publish tab to "Finalize" - which is what we have currently in prod 
- [x] - [x] One-click plan creation from the Funder Requirements page gives an error: `Error: Unable to create the plan. Org must exist`
- [x] - [x] Some public plans look like they have problems with the Creators and Affiliation data. For example, compare [this](https://dmptool-stg.cdlib.org/plans/60605/export.pdf?export%5Bquestion_headings%5D=true) public plan on stage with[ the version](https://dmptool.org/plans/60605/export.pdf?export%5Bquestion_headings%5D=true) on production. In these instances, there is an entry for "DMPTool Researcher, and Univesity of California, Office of the President (UCOP)
- [x] - [x] FOr downloaded plans, the Creator data is displaying twice and is displaying html. For example, `Creator:Natalie Meyers - <strong>ORCID:</strong> <a
href="https://orcid.org/0000-0001-6441-6716" target="_blank">[0000-
0001-6441-6716](https://orcid.org/0000-0001-6441-6716)</a>`From [this plan](https://dmptool-stg.cdlib.org/plans/35584/export.pdf?export%5Bquestion_headings%5D=true). 
- [x] Sync translations with translation.io
- [x] - [x] Minor thing, but I noticed that the notification banner has an "X" which makes it seem like you can click it away, but this does not work. For example, after you sign in it reads: "Successfully signed in." Can we either add that functionality or get rid of the "X"? 
- [x] - [x] Please change the intro text on the public plans page. We need to be clear that these plans are not vetted for adherence. The updated text should read: "Public DMPs are plans created using the DMPTool service and shared publicly by their owners. They are not vetted for quality, completeness, or adherence to funder guidelines." 
- [x] After creating a plan with no funder, I am unable to manually add a Funder on the Project Details page. The following message appears, but the values do not display when I type in the box "Please select an item from the list or check the box below and provide a name for your institution."
- [x]  - [x]The pagination formatting is broken on the repository selector window.
![screenshot-dmptool-stg cdlib org-2022 02 10-12_13_15](https://user-images.githubusercontent.com/27511575/153488957-d1f6e55b-06bd-42a3-8f3c-281f4c816bf4.png)
- [x] [x]When Creating a Plan the message "Please select an item from the list." under the Research Organization appears even if there is a value in the field. 
 - [x]  - [x]  This is not a bug with this version, but wondering if we can change the default font size for pdf export to 11 point? It is currently set to 10, which does not comply with funder reqs. 
 - [x]  - [x] Plans that were shared at the organizational level do not open when you click on the PDF icon. A tester reported she got a 406 error, when I try it just does not open. This was under the UC Berkeley account and for the following 2 plans: [42477](https://dmptool-stg.cdlib.org/plans/42477/export.pdf?export[question_headings]=true) and [30912](https://dmptool-stg.cdlib.org/plans/30912/export.pdf?export%5Bquestion_headings%5D=true). 
 - [x] I am unable to download funder template as Word or PDF files from the Funder Requirements page. When I click on the icon it opens a blank window. This happens both when I'm logged in and not.
 - [x] Reset password page not displaying errors (e.g. password too short, passwords don't match, etc.)
 - [x] Add email confirmation for successful password change
 - [x] Unable to create a new account with an institution that is not on the list. When I try it displays an error "Error: Unable to create your account!"
 - [x] On the Edit Profile page, if you go in to edit your name or institution it also requires that you change your password in order to edit any of the other fields on this page.
 - [x] On the [Help page](https://dmptool-stg.cdlib.org/help) add a bullet point to "Contact Us" which should point to: https://dmptool-stg.cdlib.org/contact-us
 - [x] [x] When creating a new plan, the Funding Organization list does not populate when I type into the box. 
 - [x] [x] When in the Finalize tab I tried to navigate back to the Project Details and got this error.  This was at 3:10pm on 2/11 for [this](https://dmptool-stg.cdlib.org/plans/74671/publish) plan 
```
Proxy Error The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request Reason: Error reading from remote server
Apache/2.4.52 () Server at dmptool-stg.cdlib.org Port 443
```
 - [x] [x] Last tab in the Create Plan workflow should be "Finalize / Publish", so just add the "Publish" part 
 - [x] [x]I have a value in the Funder field on the Project Details tab but when I go back to edit another field on this page it still displays the "Please select an item from the list or check the box below and provide a name for your institution." message. This is for [this plan
](https://dmptool-stg.cdlib.org/plans/74671)
 - [x] Tring to add a Related Work to the same plan as above gets a never-ending loading icon. This may be related to the above Funder issue and not the Related Work, I am not sure.
 - [x] Requesting feedback on a plan gets the following error message: `Project-Id-Version: dmptool 1.0 Report-Msgid-Bugs-To: contact@translation.io POT-Creation-Date: 2022-02-09 08:59-0800 PO-Revision-Date: 2022-02-09 17:59+0100 Last-Translator: FULL NAME Language-Team: English Language: en_US MIME-Version: 1.0 Content-Type: text/plain; charset=UTF-8 Content-Transfer-Encoding: 8bit Plural-Forms: nplurals=2; plural=n!=1;`
 - [x] Is it possible to change the Affiliation field in the Customizable Templates to point to only funders and orgs with existing accounts? Similar to the Create Plan funder selection? Right now it points to all of ROR (I think) and is hard if find the correct template.
 - [x] Org admin New Org and Merge Org screens have alignment off for Org selector
 - [x] I tried adding an application notification and it displays two bars, with the body of the notification displaying once, and the other line is blank. The notification is [here](https://dmptool-stg.cdlib.org/super_admin/notifications/13/edit). 
 - [x] When creating a new plan, my organization (currently NIH) is auto-populating the research organization field, however, I am unable to create the plan and instead receive the "Please select an item from the list" error message. If I manually update that field and select a new value I am then able to Create the plan. 
 - [x] Issue with downloading funder templates from the FUnder Requirements page. When trying to download the template it redirects to the main Funder Requirement page URL and displays an error message "You are not authorized to export that template". This happens when I am not logged in
 - [x] Update Recaptcha to just use checkbox
 - [x] Default all notifications to the 'Info' level

**Comment by briri** [comment]
The 'DMPTool Researcher, and Univesity of California, Office of the President (UCOP)' plan owner you're seeing in stage is due to thee process of syncing stage up with production data. The easiest way for me to do that was to ignore the users table (so as not to wipe out everyone's passwords on stage). 
The plans with DMPTool Researcher listed as the owner were plans that were copied over that had an owner who is not in the stage DB.

I can spend further time on the sync process if you'd like to pull in the new users

**Comment by mariapraetzellis** [comment]
Thanks for the details re the DMPTool Research listed as the plan owner. Sorry, I think you'd explained that before! No need to fix it in stage if it won't be an issue in prod.

**Comment by briri** [comment]
New wording about featured plans (for org admins):
"Featured plans are displayed first on the 'Public DMPs' page. A plan must be publicly visible to be 'featured'."
