### ISSUE TITLE
Sometimes unable to change or rest password 

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#329]
In certain scenarios it seems that users cannot reset their password. They get an error stating that they must 'Accept terms and conditions' but there is not checkbox for that. 
Also seeing issues where attempting to change the password on the profile page is not saving even though it says 'success' and in other situations it reports the 'Accept terms and conditions' error.

Issue is likely in the routing within the customizations to the `users/passwords_controller.rb`

**Comment by briri** [comment]
Also need to change the edit profile page so that users who have connected via SSO do not need to provide their password to change their email address

**Comment by briri** [comment]
Updated to address issues with editing password on the profile page and removed the password section entirely for user's who created their account via SSO

**Comment by VeloSteve** [comment]
I'm a little confused.  Is this closed or in progress?  Or are those not mutually exclusive?
I am definitely seeing this bug today (26 Apr 2022).
