### ISSUE TITLE
Comments are lost when when page refreshes with no warning

### ISSUE THREAD

**Issue by collinschwantes** [CDLUC3/dmptool#330]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
Version: v3.4.3

**Expected behaviour:**
Expect a warning about unsaved comments or caching in some way so that accidentally navigating away from a section does not delete the contents of the unsaved comment. 

**Actual behaviour:**
Refreshing a page or navigating forward or backward causes unsaved comments to be lost.

**Steps to reproduce:**
Comment on the response to a question in a DMP, then refresh the page.

**Comment by briri** [comment]
This is true for every field on the site. If we were to implement a warning message here, it should be done everywhere.
This is related to an issue in the DMPRoadmap repository that discusses confusion between the auto-save behaviour we have implemented on the 'Write Plan' tab for answers and manual 'Save' buttons everywhere else
