### ISSUE TITLE
Links within logos do not update

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#337]
A DMPTool admin reported that they have updated the URLs listed on their organizational profile, but the link when you click on their logo w/in the DMPTool application still goes to an old URL. This is occurring for https://dmptool.org/org/admin/88/admin_edit.

**Comment by briri** [comment]
We used to have a separate field for admins to manage the homepage URL. This was replaced in favor of using the one ROR has on record. This value is now used to help identify new users via their email domain so allowing users to change it would potentially have negative side effects.

Changing it to work off of one of the links the user enters would require us to add an additional field to the page and to indicate which of those links points to the homepage

**Comment by mariapraetzellis** [comment]
We will update these manually as they come up. This is not a problem going forward, only older institutions
