### ISSUE TITLE
Contact Us form gives error via Chrome

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#338]
A user reported that they get an error message when trying to submit a Contact Us form via Chrome. I tested this and was able to reproduce this in Chrome. It worked as expected via Safari and Firefox. 
<img width="1217" alt="Screen Shot 2022-04-07 at 5 54 34 PM" src="https://user-images.githubusercontent.com/27511575/162342570-747fd0f5-830f-4b8c-b263-42b63d95403a.png">

**Comment by briri** [comment]
The new version of reCaptcha v3 only supports the 2 most recent versions of the major browsers. I just verified that I got the same error when using Chrome. 

I then went to the 'Chrome -> About Google Chrome' menu and it started to update the browser. It apparently does not auto-update (at least in older versions) until you visit this menu page 🙄 

After the update the Recpatcha error is no longer happening.

I have altered the error message to address this: `Invalid security check! Please make sure your browser is up to date and then try again.`
