### ISSUE TITLE
The :accept_terms flag is incorrectly being set to false 

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#342]
For some reason the users.accept_terms flag is being set to false and users then receive an error stating that the terms must be accepted when they try to change their password.

**Comment by mariapraetzellis** [comment]
I'm also seeing this when trying to update a user's Institution.
![Screen Shot 2022-05-05 at 10 16 06 AM](https://user-images.githubusercontent.com/27511575/166978228-261d9568-384c-4a2b-b910-8016b554a52c.png)

**Comment by briri** [comment]
Need to add the Accept terms checkbox and link to the reset password page (and then also add it as a hidden field set to true on the profile page)

**Comment by briri** [comment]
sometimes Devise can be really painful to work with. The Devise reset password controller/model logic does not allow for any additional fields beyond password and the confirmation password. 

Had to override the core Devise logic to set the accept terms to true after the password reset. 

The Devise logic for thee rendering of the reset password page though uses encryption algorithms to convert the reset token to a matching database value and then always returns an empty resource to the view whose accept_terms is always false (the default for a new record) so we can't add any logic that decides whether or not to display the checkbox :/ 

So I just added it as a hidden field that is always set to true in the view and then updated the controller logic to work with it
