### ISSUE TITLE
Printing issue

### ISSUE THREAD

**Issue by wingfranky** [CDLUC3/dmptool#343]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
3.1.10 (Note: Also note the same problem in dmptool.org)

**Expected behaviour:**
The printout should look similar to the one in the browser.

**Actual behaviour:**
The printout is unstyled and displays loading icons.

**Steps to reproduce:**
Open any page in DMPTool in Chrome (or any other browser), click Print (Ctrl + P)

**Comment by briri** [comment]
This will require the addition of print specific CSS
