### ISSUE TITLE
License selector not filtering

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#346]
On the Research Outputs tab the License field should auto-filter all of the CC licenses first, but this feature got overwritten in a recent update. 
![Screen Shot 2022-05-05 at 2 03 09 PM](https://user-images.githubusercontent.com/27511575/167025248-02c62721-3816-4034-ba9a-fec7c96d0cff.png)

**Comment by briri** [comment]
issue was with a change to the format string token for Rubocop. It had been `CC0-%<latest>s` but switched to `CC0-%{latest}`
