### ISSUE TITLE
Creator field is pulling in HTML in PDF download

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#347]
When downloaded as a PDF file, the Creator field displays code.
![Screen Shot 2022-05-05 at 2 45 56 PM](https://user-images.githubusercontent.com/27511575/167030900-d6919397-4768-4337-baa4-dbd9ea868e16.png)

**Comment by briri** [comment]
caused by a merge conflict with DMPRoadmap with some custom code that adds the ORCID
