### ISSUE TITLE
main.css file origination

### ISSUE THREAD

**Issue by miggall** [CDLUC3/dmptool#351]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
dmptool 3.5.6

I'm looking at the branding and css overrides however it appears there's a main.css in the public folder that doesn't seem to be generated from scss compilation. Where does this main.css stylesheet originate from?

As an example, if you inspect via browser tools, you can view the "Sign in / Sign up" and see it has a color of #105e8e. That doesn't come from any scss file I can see. This creates a bit of a problem with color overrides.

**Comment by briri** [comment]
Hi @miggall, the main.css and main.js files (along with some fonts and other images) are copied over from a [separate repository](https://github.com/cdlib/dmptool-ui) that our UX team built for us. It is unfortunately managed outside the Rails asset compilation processes.

For your branding, I would recommend changing those files directly in your instance, or forking this other repo and adjusting as necessary. The repo contains a shell script to aide with building the resources and copying them over to the DMPTool repo.

**Comment by miggall** [comment]
Awesome. I had been editing that directly and building our DMPTool instance. I'll continue down that path. I just wanted to make sure I didn't miss anything.
