### ISSUE TITLE
Modifying a DMP does not Change "Last Modification Date"

### ISSUE THREAD

**Issue by shlake** [CDLUC3/dmptool#38]
Modifying a DMP template does not change the last modification date. When I submitted my DMP, the date changed. 

Is the last modification date tied to a state change? Shouldn't it be tied to ANY change in the DMP, state of DMP OR contents (overview) or details?

**Comment by mxsstrong** [comment]
the following items were addressed in this issues:
1) When modifying DMP details, the DMP last modification date displayed on the My DMPs page is not being updated, unless there is a state change.  The DMP last modification date displayed should reflect a change to the DMP if details were updated.  
2) if the dmp template overview is modified the modified date of the template should be updated (the value is being updated correctly in the db)
3) if a dmp template is modified the last modification date displayed is incorrect. ensure the last modification date is displayed (the value is being updated correctly in the db).
