### ISSUE TITLE
Upgrade MySQL to 8.x

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#380]
Upgrade MySQL from 5.7.33 to 8.0.x.

This is a infrastructure change and does not require any modifications to the Rails application at this point.

**Comment by briri** [comment]
The dev and stage instances were successfully updated with not noticeable effect on those applications

**Comment by ashleygould** [comment]
prod upgrade scheduled for thurs Nov 10: https://github.com/cdlib/cdlsys/issues/39

**Comment by briri** [comment]
upgrade complete
