### ISSUE TITLE
DMPTool Rails 6 infrastructure changes

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#382]
We will be upgrading the DMPTool system from Rails 5.2 to 6.1.

Need to update puppet hiera file to use bundler 2.3.20 and ruby 2.7.6.

Proposed approach:
- Deregister `02x2` host from the ALB
- Disable puppet on `02x2`
- Update the Puppet hiera file to tag 4.x and bump the bundler and ruby versions
- Run puppet deploy on `01x2`
- Test/verify that the application is working
- Leave `02x2` offline for a few days (just in case)
- Once satisfied with performance of the upgraded system, re-enable puppet on `02x2`, run puppet deploy, and register with ALB

**Comment by briri** [comment]
[Rails upgrade notes ... thing to watch for](https://github.com/DMPRoadmap/roadmap/wiki/Rails-Upgrade-Notes)

**Comment by ashleygould** [comment]
completed Nov 18
