### ISSUE TITLE
Users unable to edit their personal details

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#383]
A user reported that they could not change their last name in the Personal Details section because the system forces them to accept terms and conditions, but this doesn't appear on the page. 
![Screen Shot 2022-09-29 at 11 51 33 AM](https://user-images.githubusercontent.com/27511575/193118124-1d298f5e-8b19-4a92-9ec7-9a937c0d0b7d.png)

**Comment by briri** [comment]
Accept terms are being set to false somehow. 

The following query can be used to identify the effected users:
`select * from users where current_sign_in_ip is not null and (accept_terms = 0 or accept_terms is null);`

Propose updating this page to always show the accept terms checkbox if it is false in the database.
