### ISSUE TITLE
[Question] re: API documentation | token scopes

### ISSUE THREAD

**Issue by TSSlade** [CDLUC3/dmptool#387]
The [API Authentication](https://github.com/CDLUC3/dmptool/wiki/API-Authentication) page currently lists three scopes for _Standard Access_ tokens:
- public
- read_dmps
- create_dmps

Currently hitting `public` and `read_dmps` generates tokens as expected.

Currently hitting `create_dmps` generates an `invalid_scope` error:
```
curl -v https://dmptool.org/oauth/token \ 
-X POST \
-H "Accept: application/json" \
-d "grant_type=client_credentials&scope=create_dmps&client_id=$DMPTOOL_CLIENT_ID&client_secret=$DMPTOOL_CLIENT_SECRET"

{
    "error": "invalid_scope",
    "error_description": "The requested scope is invalid, unknown, or malformed."
}
```

Is the `create_dmps` scope indeed still valid at this time?

**Comment by briri** [comment]
@TSSlade apologies for my late response here. `create_dmps` is a valid scope but requires a super admin at the moment to enable it for an API client. I will email you with some info
