### ISSUE TITLE
Get a list of all templates customized by an admin and/or institution

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#40]
<a href="https://github.com/stephaniesimms"><img src="https://avatars1.githubusercontent.com/u/12703638?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [stephaniesimms](https://github.com/stephaniesimms)**
_Tuesday Nov 24, 2015 at 19:33 GMT_
_Originally opened as https://github.com/CDLUC3/dmptool/issues/168_

----

From A. Mickle Askbot FAQ:
Is there a way to get a listing of all the templates I've customized, or that someone in my organization has customized?

**Comment by stephaniesimms** [comment]
can filter customized templates now
