### ISSUE TITLE
Change section header for example answers in templates

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#402]
Currently, when example answers are included in a template, the section is titled with the name of the organization owning the template.  For example, "NIH example answer." This is misleading since we make templates on behalf of funders, so the org name is the funder's name and makes it seem like the funder has supplied the example text, which they have not.

Please change the text to just "Example answer." 
 
<img width="839" alt="Screen Shot 2022-12-01 at 3 00 54 PM" src="https://user-images.githubusercontent.com/27511575/205177649-6e65d2cb-8844-41cf-8c37-d8205b13ab71.png">

**Comment by briri** [comment]
Changed to just read 'Example answer'.
![Uploading Screen Shot 2022-12-05 at 9.04.39 AM.png…]()
