### ISSUE TITLE
Research outputs are not dowloading as csv

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#406]
A user reported that the Research Outputs are not included when selecting the CSV download option.

**Comment by briri** [comment]
Added research output and related works below the plan's narrative.
<img width="839" alt="Screen Shot 2023-01-03 at 9 30 46 AM" src="https://user-images.githubusercontent.com/1204467/210410120-f7bad498-7e77-4650-ba13-c1b7612cfc93.png">
