### ISSUE TITLE
mail error in mailer.rb

### ISSUE THREAD

**Issue by miggall** [CDLUC3/dmptool#415]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v4.0.3)**

**Expected behaviour:**
expect mail to send with properly configured sendmail system

**Actual behaviour:**
errors out
ArgumentError (:arguments expected to be an Array of individual string args):

I'm running v4.0.3 (I did not have this problem in v4.0.1)
Are there any environment settings that need to be added in this version?

**Comment by briri** [comment]
Hey @miggall 

We haven't experienced that on our systems. It does look like there was an update to the 'mail' gem. Here was the change:

<img width="350" alt="Screen Shot 2022-12-19 at 4 03 19 PM" src="https://user-images.githubusercontent.com/1204467/208551424-4bd0e68d-c1d3-4336-b64a-241aae0b5a48.png">

And it looks like they have an open issue with sendmail args on their site: https://github.com/mikel/mail/issues/1538

It didn't look like any of the other gems had a hard dependency on v2.8+, so I would suggest pegging it back at that 2.7 version for your instance. You can do that by adding a `gem 'mail', '~> 2.7'` in your Gemfile and then rerunning bundle install

**Comment by miggall** [comment]
Thank you. I ended up adding the individual arguments like
` arguments: ['-i', '-t']`. I'm sure I'll have to revert when they fix the bug
