### ISSUE TITLE
Bug with URLs in Request Feedback

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#431]
A user reported a bug (which I can reproduce) in the Request Feeback section.

Steps to reproduce:
1. In the UCOP account - request feedback on a plan
2. Click on the dmptool link
3. This goes to a 404

**Comment by briri** [comment]
can you share the contents of the email (including the bad link)?

**Comment by mariapraetzellis** [comment]
The user who originally reported this bug was trying to add a link to his internal site to the Feedback Request email.

> In the “Message” text that appears to the user when they request feedback, I was attempting to link the highlighted text out to our organization’s resource page on data management. When I have something linked (using the link button) and then go back in to test “Request Feedback,” pressing the button leads to the error:

![image](https://user-images.githubusercontent.com/27511575/221237136-10a6a712-3842-425c-b9d3-e1bb44a33af8.png)
![image](https://user-images.githubusercontent.com/27511575/221237197-e5f22f18-8e98-4a62-9c07-d37edee594b6.png)

**Comment by briri** [comment]
I'm unable to replicate this issue. I can add links to the message and the page loads ok. Perhaps there is something wrong with the URL. Can you have them send the URL they want to use?
