### ISSUE TITLE
Reset download plan defaults 

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#435]
Since so many users are creating plans for NIH, we need to adjust our default download settings to accommodate NIH requirements/recommendations.

- Plans should default to only including the answered question text. "question text (will only display your answers)"
- Currently, the "question text (will only display your answers)" option only works if you uncheck the box. This should be switched.

**Comment by briri** [comment]
<img width="388" alt="Screenshot 2023-04-04 at 1 55 54 PM" src="https://user-images.githubusercontent.com/1204467/229918926-e1871250-f7fa-4262-b510-699012468109.png">

@mariapraetzellis let me know if you want to change any of the wording or what defaults are set. The 2 checked items are on by default right now

**Comment by mariapraetzellis** [comment]
I tested the download settings, and they worked as expected. The new language is good and clear.
