### ISSUE TITLE
Look into using FAIRsharing for metadata standards

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#436]
Please look into the FAIRSharing API and think about if it would be possible to replace the existing metadata registry we're using with this one. It's much bigger registry and appears to have good metadata attached to it.

https://fairsharing.org/API_doc

**Comment by briri** [comment]
Will need to crosswalk existing RDA standards to the FAIRSharing standards and/or get rid of the join table and instead store the entire standard metadata so we can still support the old standards.

If we crosswalk we will need to up the DMP IDs (DOIs).
