### ISSUE TITLE
Specific data types for FDP

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#437]
One of the FDP templates, created by NCI, has a list of specific data types that they are interested in having appear on the Research Outputs tab. These are more areas of research than types of outputs, so I'm not sure where best to put it. Let's discuss. 

![image](https://user-images.githubusercontent.com/27511575/221283161-b5a07e12-db5e-46cd-924a-617c76db2b34.png)

**Comment by mariapraetzellis** [comment]
We can add these fields as options for when we allow admins to determine what data types appear in the RO list.

**Comment by briri** [comment]
We need to allow organizational administrators to replace the list of default research output types, or add additional types to the default list.

Here is a screenshot of the select box a researcher currently interacts with when editing/adding a research output:
<img width="610" alt="Screenshot 2023-03-14 at 8 34 23 AM" src="https://user-images.githubusercontent.com/1204467/225053748-f2fd0583-ca19-4d08-874d-b815dddebc75.png">

Please refer to the [spec document](https://docs.google.com/document/d/1eNc90-ccFX-GNJz58TyLALafZ7LM0xgYCGMZE2wPY7w/edit#heading=h.beiillb0lxym) for some ideas on implementation.

This will require the creation of a new table that stores the template_id foreign key and the value of the type. When the admin wants to append their entries to the default list, the code should add an entry for each default type to this table . This will ensure that changes to the default list do not change the admin's selections over time. 

The current output types are defined as an enum on the [research_output model](https://github.com/CDLUC3/dmptool/blob/23327b2dae9dcd00d8bd7fab18301868680999ce/app/models/research_output.rb#L41). If it makes things easier, those values can be moved into a separate table of their own. 

The template model will then need to be updated to ensure that the [version method](https://github.com/CDLUC3/dmptool/blob/23327b2dae9dcd00d8bd7fab18301868680999ce/app/models/template.rb#L400) is still working and does not require any changes needed to accommodate the new values. The Template's [deep_copy method](https://github.com/CDLUC3/dmptool/blob/23327b2dae9dcd00d8bd7fab18301868680999ce/app/models/template.rb#L292) should also be updated to ensure that the values in the table are carried forward to new versions.

Once the admin components are in place, the research outputs view and controller will need to be updated to fetch the correct values.
