### ISSUE TITLE
Terry Onboarding for FDP Functionality

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/dmptool#439]
Kickoff for FDP work of work Tues Mar 14

- The work to be done
  - [Add ability for admins to filter repositories list](https://docs.google.com/document/d/1XuQaFRhqZAffIe6Es-egYfnmRSkIWvt5QFg0wYkrgkM/edit#heading=h.beiillb0lxym) - older spec written for potential contributor who ended up not contributing
  - [Extended FDP functionality](https://github.com/CDLUC3/dmptool/issues/437)

- Onboard to DMPTool
  - Dev environment set up
    - https://github.com/CDLUC3/dmptool
  - Any Rails training that needs to take place for this work?

- Product Management Workflow for team, meetings, standups, etc

- Timeline of work
  - Mar 13, 2023 Terry can begin
  - 3 sprints for work - project board here? https://github.com/orgs/CDLUC3/projects/12/views/1
  - Complete end of April - Terry OOO beginning Wed Apr 19, 2023 - May 2, 2023

**Comment by briri** [comment]
The work to be done doc has been updated. Please refer to [this version](https://docs.google.com/document/d/1eNc90-ccFX-GNJz58TyLALafZ7LM0xgYCGMZE2wPY7w/edit?usp=sharing) instead which includes all of the tasks FDP wants us to accomplish.

**Comment by marisastrong** [comment]
Terry was already a member of the dmp role https://github.com/cdlib/cdlsys/issues/149 so he should be all set with access.
