### ISSUE TITLE
Add a new 'Preferences' tab to the Template admin page

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#441]
Add a new 'Preferences' tab to the page that organizational admins use when editing their own templates or when customizing a funder's template.

The change will need to be made to the template navigation partial.

**Comment by terrywbrady** [comment]
I have created new text fields for the Research Outputs Guidance.  Note that I currently have tinymce enabled.

<img width="1514" alt="image" src="https://user-images.githubusercontent.com/1111057/226060897-4a39273f-02d9-49d3-bcb3-751c43c6b88d.png">

Where should this guidance appear?  

- Appear above output type?
- Appear as a tool tip on the type selector?
- Appear on the right hand side like the current "comments and guidance"?

If the guidance is to appear as a tooltip, I think the guidance needs to be plain text (no links, lists, tables).

![image](https://user-images.githubusercontent.com/1111057/226061191-eedd96b2-310a-4070-bf1c-874f23411624.png)

Note that I have created the following fields in my PR:
- End User Guidance for Research Outputs
  - TODO: rename this as End User Guidance for Output Types
- End User Guidance for Repositories
- End User Guidance for Metadata Standards
- End User Guidance for Licenses

**Comment by mariapraetzellis** [comment]
@terrywbrady This should function as a tooltip and appear just to the right of the field.

**Comment by terrywbrady** [comment]
Thanks @mariapraetzellis .  For the Output Type, should the tooltip go on each field or just on the select box?

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/1111057/227335756-bd1985ce-6438-4887-aa37-6c63ad3b00d5.png">

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/1111057/227335863-eabaf17c-5d2a-4cc8-a40c-4093d5bc467f.png">

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/1111057/227335978-0e614713-dc25-4540-a773-9bceff2e54c5.png">

**Comment by terrywbrady** [comment]
## Other Tooltip Placement Questions

To start the conversation, I have inserted the tooltip on the page. I am not confident that it is in the correct place.

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/1111057/228383948-1c316f70-dc16-46ff-bdf6-41882aac7df0.png">

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/1111057/228383990-18621659-27ef-44f8-ae4a-b7e1da821123.png">

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/1111057/228384038-2b733ea7-8f30-412f-8f33-cbf442115027.png">

**Comment by terrywbrady** [comment]
Terry and Maria discussed tooltip placement.  New issues/tickets have been created.

**Comment by mariapraetzellis** [comment]
@terrywbrady The Preferences tab should also be available for administrators who customize funder templates they did not create. For example, in this case, I am logged into the tool as a UCOP administrator and want to add customizations to this template: Department of Energy (DOE): Office of Science.
  
<img width="1155" alt="Screen Shot 2023-04-11 at 2 25 54 PM" src="https://user-images.githubusercontent.com/27511575/231291919-8fa35838-b58e-40bb-acd3-d784df9f3a4e.png">

**Comment by mariapraetzellis** [comment]
I tested and confirmed that the following features are working as expected:

- [x] Ability to hide the research outputs tab
- [x] Tooltips work and good placement
- [x] Repository preferences are working as expected 
- [x] Metadata Standard preferences are working as expected 

Small change: can you fix the success message that appears when adding a Research Output? It currently reads: "Successfully added the researchoutput" and just needs to be split into two words "research output".

**Comment by terrywbrady** [comment]
@briri , what permission check would I need to make to enable the tab as Maria requested?

I am currently checking `template_modifiable`

```
  <% if template_modifiable?(template) %>
    <li role="presentation" <%= active_page?(new_org_admin_template_phase_path(template.id)) ? ' class=active' : '' %>>
      <%= link_to(_('Add new phase'), new_org_admin_template_phase_path(template.id), { 'aria-controls': 'add_phase', role: 'tab' }) %>
    </li>
    <li role="presentation" <%= active_page?(preferences_org_admin_template_path(template.id)) ? ' class=active' : '' %>>
      <%= link_to(_('Preferences'), preferences_org_admin_template_path(template.id), { 'aria-controls': 'preferences', role: 'tab' }) %>
    </li>
  <% end %>

```

**Comment by terrywbrady** [comment]
Adding:
```
  def obj_name_for_display(obj)
    display_name = {
      ...
      ResearchOutput: _('Research Output'),
    }
```

**Comment by briri** [comment]
@terrywbrady, that `template_modifiable?` is preventing the preferences tab from appearing when the admin is trying to customize a template. You should probably use `template.latest? && template.id.present? && template.org_id = current_user.org.id` instead. This will just prevent it from appearing for historical versions and if the user is somehow viewing a template/customization that they do not own.

@mariapraetzellis I'm not sure if we've thought through this or not but, should an admin who is customizing a template be able to modify the preferences set by a funder admin? For example, if you set preferences for the FDP template, should an admin from Berkeley be able to add their own repositories, licenses, etc. or remove preferences you have defined?

**Comment by terrywbrady** [comment]
@briri , I added this change https://github.com/CDLUC3/dmptool/commit/0807decf324203dabf4a4768ffc2ddb565eed830

Question, if you look at my policy rules, and I checking all of the right permissions or do these rules need to be stricter?

https://github.com/CDLUC3/dmptool/blob/tbstart5/app/policies/template_policy.rb#L12-L26

**Comment by briri** [comment]
Yes, those are the correct permissions @terrywbrady
