### ISSUE TITLE
Add ability for org admin to disable/hide research outputs

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#442]
We need to allow organizational admins to specify that they do not want users of their template to see the research outputs tab.

<img width="609" alt="Screenshot 2023-03-14 at 8 18 00 AM" src="https://user-images.githubusercontent.com/1204467/225048720-a97c5589-d092-4e0e-882e-1affcaaeaef3.png">
_Example of a researcher's DMP with the 'Research Outputs' tab visible_

Please refer to the [spec document](https://docs.google.com/document/d/1eNc90-ccFX-GNJz58TyLALafZ7LM0xgYCGMZE2wPY7w/edit#heading=h.beiillb0lxym) for some ideas on implementation.

A new boolean column will need to be added to the `templates` table so that we can store whether or not the tab is displayable. The change should trigger the generation of a new version of the template that the admin needs to publish. To do this, use the existing [finder helper method](https://github.com/CDLUC3/dmptool/blob/23327b2dae9dcd00d8bd7fab18301868680999ce/app/models/template.rb#L254) and then check the [version method](https://github.com/CDLUC3/dmptool/blob/23327b2dae9dcd00d8bd7fab18301868680999ce/app/models/template.rb#L400) to see if there are any changes needed to accommodate the new value. The Template's [deep_copy method](https://github.com/CDLUC3/dmptool/blob/23327b2dae9dcd00d8bd7fab18301868680999ce/app/models/template.rb#L292) should also be updated to ensure that the value of the boolean is carried forward to new versions.

Note that this functionality needs to happen for both templates owned by the Org and with their customizations of funder templates!

Once the admin changes are in place, the plan navigation view will need to be updated to adhere to the value of the new boolean field.

**Comment by terrywbrady** [comment]
@briri , 

@mariapraetzellis mentioned that the Enable Research Outputs flag should only apply prospectively.  My approach to this was to saw show the tab IF either is true: (1)enable RO is true for the template OR (2)the plan has at least one RO attached.

```
  <% if Rails.configuration.x.enable_research_outputs && (plan.template.enable_research_outputs? || plan.research_outputs.length > 0) %>

``` 

I added a separate item to remind myself about the deep copy.  I am not yet ready to test that.

**Comment by briri** [comment]
Yes I think that makes sense @terrywbrady if the plan does for some reason already research outputs defined we should show the tab.

**Comment by mariapraetzellis** [comment]
This looks good and is working as expected. We will need it to appear for templates within the user's organization and templates that they can customize.
