### ISSUE TITLE
Display Hand Cursor when hovering over a hypertext link in DMP

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/dmptool#445]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

Version: v4.0.7

**Expected behaviour:**

See hand cursor when hovering over a hypertext link

**Actual behaviour:**

When hovering over a hypertext link in DMP Tool, the crosshairs cursor is visible.  

**Steps to reproduce:**

Open home page in Chrome, hover over link text.  Note the crosshairs cursor.  Hover over a button.  Note the hand cursor.

**Comment by briri** [comment]
It shows the hand icon in Safari, so this may be a browser specific issue.

**Comment by mariapraetzellis** [comment]
Looks good.
