### ISSUE TITLE
Plan / Follow-up Tab: Existing Research Outputs are lost when adding a new Research Output

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/dmptool#447]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

v4.0.7

**Expected behaviour:**

Plan / Follow-up Tab: The list of Research Outputs should be modifiable.

**Actual behaviour:**

Plan / Follow-up Tab: Existing Research Outputs are lost when adding a new Research Output

**Steps to reproduce:**

1. Save some Research Outputs on the Follow-up tab.
2. Return to the tab
3. Add new Research Outputs and Save
4. Note the changes to the list

**Comment by briri** [comment]
figured out the issue. I had neglected to include all of the existing related identifier values as hidden fields. The form submission was just taking whatever was passed and replacing what it had.

Thanks for bringing this to my attention @terrywbrady

**Comment by briri** [comment]
Noting here that the items being lost are 'related identifier' not 'research outputs'

**Comment by mariapraetzellis** [comment]
I tested this and can now add new Research Outputs to an existing list under the Follow-Up tab. The additional outputs are added and do not remove any existing outputs.

**Comment by Br-Johnson** [comment]
I tested this just now, and when I added a new article to our research outputs and it did stick without wiping out the others! :) 

However :( there are also now a number of un-related research outputs listed that I did not put there (though the unrelated research outputs do not appear in our final DMP: https://doi.org/10.48321/D1CW23

One of the research outputs I didn't list is yours @mariapraetzellis, so perhaps this is a result of you doing some testing? the first two listed are outputs I entered, but the remainder I did not.

![image](https://user-images.githubusercontent.com/26495640/233680969-0fa56155-af2e-4fe6-8802-288525c746ca.png)

**Comment by briri** [comment]
very strange. Thanks for bringing this to our attention @Br-Johnson.

**Comment by briri** [comment]
This has been patched @Br-Johnson and we've run a script that re-fetched the citation information and attached it to the correct DOIs.

Please have a look at your DMP and let me know if anything still looks incorrect.

**Comment by Br-Johnson** [comment]
Looks like it works great now. Thanks for this!
