### ISSUE TITLE
Add ability for researchers to include free text answers for Repositories and Metadata Standards

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#466]
As part of the FDP pilot, NCI has requested that we add the ability for researchers to input repositories and metadata standards that do not appear in the listing. This is needed because there are many local IRs and other smaller repositories that are not listed, and creating a completely comprehensive list is not possible. This would be an issue for other templates as well, so adding it as a feature has general utility.

This could be a checkbox on the Repository search page that reads "My repository is not listed" and when selected, a free text field appears below.

**Comment by briri** [comment]
repurpose the custom repository functionality on the new template preferences page
