### ISSUE TITLE
Downloading Users as an org admin hits a 502 Proxy Error 

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#467]
Several users have reported hitting proxy errors when trying to download the list of users. To reproduce this, I had to make myself an org admin of their account (University of Pittsburg). I did not hit the proxy error when logged in as an org admin under other orgs (Tetiaroa Society)

Connected to ticket: 119123

<img width="522" alt="Screen Shot 2023-04-27 at 11 07 52 AM" src="https://user-images.githubusercontent.com/27511575/234953699-61113538-9362-43b7-ab65-7da33c86b422.png">

**Comment by briri** [comment]
this is related to the proxy errors we've seen when downloading PDFs. These tasks require too much processing power and clog up our puma workers.

**Comment by briri** [comment]
Was not related to the PDF proxy errors. This was due to an n+1 query in the controller
