### ISSUE TITLE
Feature Request: hotkey for saving all form entries -->  cmd/ctrl + s

### ISSUE THREAD

**Issue by collinschwantes** [CDLUC3/dmptool#476]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
Version: v4.1.1

**Desired behaviour:**
Pressing control/cmd+s saves all responses in the form.

**Actual behaviour:**
Have to press the save button for each section.

**Comment by collinschwantes** [comment]
A second user reported unexpectedly losing a DMP. It seems like users expect materials to be autosaved or they expect a warning when navigating away from a section (project details, write plan, etc) about unsaved changes. 

I think people are jumping from the write plan tab to the request feedback tab without explicitly saving.

**Comment by mariapraetzellis** [comment]
@collinschwantes Can let us know the user name/email of the individual who lost the plan? And, clarify what you mean by losing a DMP?

**Comment by collinschwantes** [comment]
Apologies for the lack of clarity.
Losing a DMP = User was filling out their DMP then likely navigated away from the "write plan" tab before clicking the save button. All of the text they had entered into the form was lost. 

Users affected: teigen@ecohealthalliance.org; ross@ecohealthalliance.org

**Comment by briri** [comment]
We're not going to be able to address this in the current tool. We will add it to the list of desired features in the system rebuild
