### ISSUE TITLE
Limit on number of Research Outputs?

### ISSUE THREAD

**Issue by Br-Johnson** [CDLUC3/dmptool#479]
When submitting a new Research Output item (eg https://doi.org/10.1093/ve/veaa069) to the Hakai Institute Juvenile Salmon Program DMP (https://doi.org/10.48321/D1CW23) and pressing save I get a this error message in the browser:
```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server

Apache/2.4.57 () Server at dmptool.org Port 443
```
I'm just wondering if I've hit a limit to the number of Research Outputs I can include (32 included so far) or if this is a bug.

Thanks!
Brett

**Comment by briri** [comment]
thanks for reporting this @Br-Johnson 

This happens periodically when the server is slow to respond. We are investigating the root cause.

For the short term though, if you try to submit the form again it should work.

**Comment by Br-Johnson** [comment]
Ah OK gotcha. Thanks for the quick response! 

Unfortunately, I just tried again and received the same 502 Proxy error:
```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server

Apache/2.4.57 () Server at dmptool.org Port 443
```
I'll try again tomorrow and let you know what I find.

**Comment by Br-Johnson** [comment]
I am unfortunately still getting this error.

**Comment by briri** [comment]
Ok, thanks for updating us.

The code is making external calls to try and fetch the citation for every related identifier associated with the DMP. Some of the the response times can be a bit slow, and our load balancer is timing out which is why you see the proxy error.

We will need to make this process asynchronous so that it doesn't interfere with the page response.

I will keep you posted on our expected patch date. Apologies for the inconvenience

**Comment by briri** [comment]
Hi @Br-Johnson we just released a patch that should address your issue. Please let us know if you continue to have any problems.

**Comment by Br-Johnson** [comment]
Hey @briri Thanks for this! I was able to add that new research output no problem now. However, it just shows up as "Article:  https://doi.org/10.1093/ve/veaa069  - No citation available." 

Not sure if there was a bug introduced to the doi metadata service or if the doi metadata may be incompatible or corrupt on the crossref side. 

However, I added a different DOI for testing purposes and it came back as a properly formatted citation.

**Comment by briri** [comment]
Thanks for verifying that the page is no longer throwing a proxy error. For some reason that particular DOI does not return its citation information in a way that we can use it (an underlying library we use to extract the DOI bibtex reports an encoding error).

**Comment by Br-Johnson** [comment]
Thanks!
