### ISSUE TITLE
Finalize tab shows incorrect visibility if user is not the owner or co-owner

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#483]
The Finalize tab is displaying the incorrect visibility to the user when the user's access is editor, commenter or admin providing feedback.

For example if the plan is 'privately' visible an admin providing feedback sees 'organizationally'

**Comment by mariapraetzellis** [comment]
We received another ticket about this bug, so we should prioritize this fix if possible.

**Comment by briri** [comment]
Issue was with the translation files. Updated and should now display the correct visibility
