### ISSUE TITLE
Enabling Institutional Signin

### ISSUE THREAD

**Issue by rwvaldivia** [CDLUC3/dmptool#484]
Hi,

We are using a DMPTool fork version 4.0.9. At this time we need enable a institutional signin like image below,

![Institutional Signin](https://github.com/CDLUC3/dmptool/assets/1844023/0bb955c2-2f59-4e06-9c9c-2d1703a5f568)

Have an some flag in database that enable this?

tks...

**Comment by briri** [comment]
Hi @rwvaldivia 

That page gets the list of organizations from [this scope]() which looks at the `orgs.managed` field in the database. 

The checkmark that indicates that the organization is setup for SSO is determined by [this code](https://github.com/CDLUC3/dmptool/blob/9b5725f3c5199719c3097c432ae016a04ba52bd3/app/models/concerns/dmptool/org.rb#L25). Basically it is looking for a `shibboleth` identifier for the organization.
