### ISSUE TITLE
Change wording on the Finalize tab

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#485]
Only the owner of the DMP can publish the plan, this is causing confusion when co-owners can't publish. We should either gray out the option and make a note stating this for co-owners or add it to the checklist of requirements.

**Comment by briri** [comment]
Added a item to the checklist:


![Image](https://github.com/CDLUC3/dmptool/assets/1204467/c60f70cb-cd42-4566-8490-77e4aeb3e68f)
