### ISSUE TITLE
Participating organizations page not showing funder/institutions

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#486]
The participating organizations page excludes all orgs designated as a funding institution. We should change the following line to only display 'managed' orgs that are `institution_condition` or `organization_condition`.
https://github.com/CDLUC3/dmptool/blob/9b5725f3c5199719c3097c432ae016a04ba52bd3/app/controllers/dmptool/public_pages_controller.rb#L10

**Comment by mariapraetzellis** [comment]
I think if we included orgs designated as funders **and** institutions it would work as needed. If we include only funders this will include federal agencies that are not really partners since we make the templates.
