### ISSUE TITLE
Link to create a new plan redirects to dashboard

### ISSUE THREAD

**Issue by igwink** [CDLUC3/dmptool#488]
What version of the DMPRoadmap code are you running? (e.g. v2.2.0): Version: v4.1.4

Expected behaviour: From the Funder Requirements list, I want to be able to use the "Copy Link to Create a New Plan" button to generate a link to a pre-populated template that I can share with researchers. Clicking the "Create Plan" (+ button) works as intended.

Actual behaviour: Entering the URL for creating a pre-populated plan redirects to My Dashboard instead. An example link that I tried copying for creating a DOD DMP at my institution (University of Kentucky) that redirects to my dashboard:

https://dmptool.org/plans?org_autocomplete%5Bfunder_id%5D=210&org_autocomplete%5Bfunder_name%5D=United+States+Department+of+Defense+%28DOD%29+%28defense.gov%29&org_autocomplete%5Bid%5D=60&org_autocomplete%5Bname%5D=University+of+Kentucky+%28uky.edu%29&plan%5Btemplate_id%5D=1903

Steps to reproduce:
1. Go to the Funder Requirements tab.
2. Under the Create a New Plan tab, select Copy Link to Create a New Plan.
3. Paste the URL.

**Comment by mariapraetzellis** [comment]
I was able to recreate this bug following the steps described above.

**Comment by VickyRampin** [comment]
This is also an issue for us (at NYU). We have 2 custom templates that we use and both share links are broken in the same way as described in the top comment.

**Comment by briri** [comment]
Corrected issue by adding a separate controller action. Rails 6 no longer seems to support the old approach
