### ISSUE TITLE
Configuring instructions on dmp-4.0.9

### ISSUE THREAD

**Issue by fcsousaunifesp** [CDLUC3/dmptool#489]
Version of the DMPRoadmap code are you running - v4.0.9

Good afternoon, we are in the guidance stage, using conditional questions.
Could you guide us how to configure the settings that are in the attached figures?

Tanks

Flavio Castro
![imagem1](https://github.com/CDLUC3/dmptool/assets/31976288/fec05f63-ecf0-40fe-8d67-248f965fc892)
![imagem2](https://github.com/CDLUC3/dmptool/assets/31976288/7fe4c873-e0c3-4542-b1cd-5c629ac6a757)

**Comment by briri** [comment]
olá @fcsousaunifesp.

All of the themes and guidance exist in database tables. Most of them can be updated via the UI.

The 'Data sharing' and 'Preservation' categories are called 'Themes' and stored in the `themes` table in the database. They can be updated by a 'super admin' user from the `Administrador -> Temas`menu. 
<img width="263" alt="Screenshot 2023-07-12 at 2 00 04 PM" src="https://github.com/CDLUC3/dmptool/assets/1204467/73f6c885-7b1c-4e64-be43-59f26d665222">

Every Template has Questions and each Question can have 0-n themes associated with it. So for example in the screenshot you provided, the 'Which data are of long-term value and should be retained, shared and/or preserved?' question has been associated with both the 'Data sharing' and 'Preservation' themes.
For example, here is a screenshot of a template question that has been associated with multiple themes:
<img width="1337" alt="Screenshot 2023-07-12 at 2 13 21 PM" src="https://github.com/CDLUC3/dmptool/assets/1204467/ecd4e0ea-7e4d-4d4d-a75b-faae0e0f94f5">

Every institution may also have Guidance defined. Guidance is also associated with 1-n themes. In your example above, an organizational admin from Baylor has defined guidance for 'Data sharing' and 'Preservation'. 
For example, here is a screenshot of the Baylor admin's guidance page:
<img width="1414" alt="Screenshot 2023-07-12 at 2 06 21 PM" src="https://github.com/CDLUC3/dmptool/assets/1204467/86006f94-488d-46bc-884d-96b0d079ff84">

**Comment by briri** [comment]
The guidance would need to be updated for each institution separately. The ones associated with the DMPTool organization are considered to be the default guidance, so it would be best for you to change those first. I would then focus on updating any other organizations that make sense for your implementation.
