### ISSUE TITLE
Configure DMPTool with Matomo Tracking Code

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/dmptool#490]
Brian has access to the Matomo tracking code.  This needs to be configured in the DMPTool application.  

Did DMPTool get configured with a GA4 tracker?  If not, there currently is not any collection of analytics happening so sooner rather than later is best for configuration.

Here is the JavaScript Tracking code to include on all your pages. Make sure this code is embedded within a script element on every page of your website. It is recommend pasting it immediately before the closing head tag.

If you have questions you can pose them in the #matomo slack channel

- [ ] let me know if you would like export the UA data into Matomo (previous year?)

```
var _paq = window._paq = window._paq || [];
/* tracker methods like "setCustomDimension" should be called before "trackPageView" */
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
(function() {
var u="//matomo.cdlib.org/";
_paq.push(['setTrackerUrl', u+'matomo.php']);
_paq.push(['setSiteId', '20']);
var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
})();
```

**Comment by briri** [comment]
Removed old GA script and replaced with Matomo script. The script is only applicable in production and requires the following configuration to be defined in `config/dmproadmap.yaml`, the Rails credentials file, AWS SSM parameters or a dotenv file depending on how you manage your existing config.

```
  # Matomo analytics tracking
  enable_matomo: true
  matomo_url: 'matomo.my.org'
  matomo_sit_id: 1
```

**Comment by briri** [comment]
This is done
