### ISSUE TITLE
The conditional questions, they are no longer working.

### ISSUE THREAD

**Issue by fcsousaunifesp** [CDLUC3/dmptool#491]
Version of the DMPRoadmap code are you running v4.0.9

Hello goodnight.
Can you guide us?
After database update. I checked the conditional questions, they are no longer working.
What procedures can solve these problems?
Thanks
Flavio Castro

**Comment by briri** [comment]
Hi @fcsousaunifesp 
When you say they are no longer working, what do you mean? 

Are you unable to add/change them when updating a template? Are they not removing questions when the user selects the appropriate value on their plan?

Are you seeing any error messages in the Rails logs?

If it is happening when the user is editing their plan, You can check for any Javascript errors in the developer tools in your browser to see if you can see the specific error.

**Comment by fcsousaunifesp** [comment]
Hello people.
I created a new template, with conditioning questions. However, in this new model, they don't work.
Is there any guidance to activate it.
Just to inform you, the previous model and the conditioning questions are working normally.
Can you help me?

Best regards

Flavio Castro

**Comment by briri** [comment]
Hi @fcsousaunifesp
When you say they are no longer working, what do you mean?

Does it not work when you are setting/adding the conditional logic to the template or are they not working when a researcher is editing their PGD?

Are you seeing any error messages in the Rails logs?

Also check for any Javascript errors in the developer tools in your browser to see if you can see the specific error.
