### ISSUE TITLE
Bug with editing template questions on stage

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#494]
When editing a question on [this](https://dmptool-stg.cdlib.org/org_admin/templates/1854/phases/2038/edit) template in Stage, I first hit a 500 error and then, after a page refresh, displayed raw HTML. I was not able to replicate this problem in Production. 

{"html":"\u003c!--\n**Project: DMPRoadmap\n**Description: This block shows a question, its guidance, and options when multiple choice is selected.\n**Arguments transferred: 'question'\n**Copyright: Digital Curation Centre and California Digital Library\n--\u003e\n\u003cdiv class=\"row\"\u003e\n  \u003cdiv class=\"col-md-12\"\u003e\n    \u003cdiv class=\"row\"\u003e\n      \u003cdiv class=\"col-md-8\"\u003e\n        \u003cdl class=\"dl-horizontal\"\u003e\n          \u003cdt\u003eQuestion number\u003c/dt\u003e\n          \u003cdd\u003e1\u003c/dd\u003e\n          \u003cdt\u003eQuestion text\u003c/dt\u003e\n          \u003cdd\u003e\n            \u003cdiv class=\"display-readonly-textarea-content\"\u003e\n                \u003cp\u003e\u003cstrong\u003eDescribe Plan Elments below with free text. In addition, you should proceed to the Research Outputs tab to maximize description of structured information for Plan Elements whenever feasible (e.g., data types, repositories). \u003c/strong\u003e\u003c/p\u003e\r\n\u003cp\u003e\u003cstrong\u003eElement 1: Data Type  \u003c/strong\u003e \u003c/p\u003e\r\n\u003cp\u003eWill all scientific data generated by the research project be shared in a data repository that makes data available to the larger research community?  If No, explain the rationale that determines which scientific data will not be shared in the comment area below.       \u003c/p\u003e\n            \u003c/div\u003e\n          \u003c/dd\u003e\n          \u003c!-- question.option_based? --\u003e\n            \u003cdt\u003eQuestion options\u003c/dt\u003e\n            \u003cdd\u003eYes, No\u003c/dd\u003e\n          \u003c!-- Default value --\u003e\n          \u003c!-- Format title --\u003e\n          \u003cdt\u003eAnswer format\u003c/dt\u003e\n          \u003cdd\u003e\n            Dropdown.\n              Additional comment area will be displayed.\n          \u003c/dd\u003e\n\n          \u003c!-- question conditions --\u003e\n\n          \u003c!-- Suggested answer or Example--\u003e\n          \u003c!-- Guidance linked to this question --\u003e\n          \u003c!-- Themes --\u003e\n              \u003cdt\u003eThemes\u003c/dt\u003e\n              \u003cdd\u003eNo themes selected\u003c/dd\u003e\n        \u003c/dl\u003e\n      \u003c/div\u003e\n\n      \u003cdiv class=\"col-md-4\"\u003e\n          \u003cdiv class=\"panel-group\" id=\"18559-guidance\"\u003e\n            \u003ch4\u003eThemed Guidance\u003c/h4\u003e\n\n\n        \u003c/div\u003e\n            \u003cp\u003eThere is no organizational guidance related to the themes associated with this question.\u003cp\u003e\n      \u003c/div\u003e\n    \u003c/div\u003e\n\n    \u003cdiv class=\"row\"\u003e\n      \u003cdiv class=\"col-md-12\"\u003e\n      \u003c/div\u003e\n    \u003c/div\u003e\n  \u003c/div\u003e\n  \u003cdiv class=\"col-md-5\"\u003e\n  \u003c/div\u003e\n\u003c/div\u003e\n"}

**Comment by briri** [comment]
Unable to replicate in local dev environment. Need to check on stage
