### ISSUE TITLE
Insert logo in pages off pdf

### ISSUE THREAD

**Issue by fcsousaunifesp** [CDLUC3/dmptool#498]
Good night team.
We are customizing the files in pdf and we would like to insert the logo of the institutions in their respective reports. Do you have any idea how to do it?
We're running? (e.g. v4.0.9)
This is my pdf file used as an example.
[Plano_pgd_-FCS_com_certificação_orcid.pdf](https://github.com/CDLUC3/dmptool/files/12210267/Plano_pgd_-FCS_com_certificacao_orcid.pdf)
I left this screen
![logo_in_pdf](https://github.com/CDLUC3/dmptool/assets/31976288/24cb0bbd-e711-4cd8-8923-e33ebaa87ea2)

Best Regards
Flavio Castro de Sousa
Técnico em Tecnologia da Informação
Superintendência de Tecnologia da Informação
UNIFESP - Reitoria

**Comment by briri** [comment]
Hi @fcsousaunifesp we have not tried doing that here. The Rails application uses the wicked_pdf gem which runs a C program called wkhtmltopdf which runs on the server's OS to generate the PDF file. It basically converts HTML into PDF, but it does not have access to the normal Rails path's, so if you have to use absolute paths for your `<img src="???"/>`.  Here is [the documentation](https://github.com/mileszs/wicked_pdf#usage-conditions---important) about that.

Depending on your setup, the logos may be stored on the server's disk, an S3 bucket, etc. You would have to see the [gem's documentation](https://github.com/markevans/dragonfly) for how to get the path you need. It should be stored in the `orgs` table in one of the logo columns.
