### ISSUE TITLE
Customizable templates do not allow editing by the super admin.

### ISSUE THREAD

**Issue by fcsousaunifesp** [CDLUC3/dmptool#500]
**What version of the DMPRoadmap code are you running? (e.g. v4.0.9)**

Good afternoon, team.
We are faced with the following situation.
When accessing as superadmin, click on admin > templates > Customization templates > actions > Edit Customization > Customize phase.
We have not provided the edit button for the question phases.
And this way we can't edit this template, thus providing updates to our users.
However, for the other models we have the edit button active.
Can you advise us?

Best Regards 

Flavio Castro de sousa

**Comment by briri** [comment]
I'm not sure I understand your question. 

Can you provide me with a screenshot of one that is working and a screenshot for the one that is failing?

**Comment by fcsousaunifesp** [comment]
Good afternoon, screens 1 to 5 refer to the template that I can edit.

![screen_customize_1](https://github.com/CDLUC3/dmptool/assets/31976288/9d23d88b-2825-4630-93b9-82edf40e7318)

![screen_customize_2](https://github.com/CDLUC3/dmptool/assets/31976288/be005301-010b-4806-be16-1c2613de90cd)

![screen_customize_3](https://github.com/CDLUC3/dmptool/assets/31976288/0938f3b6-8455-4c31-9cfb-ede904144ae7)

![screen_customize_4](https://github.com/CDLUC3/dmptool/assets/31976288/38092921-552d-47ff-baa6-40ebb41e2b7c)

![screen_customize_5](https://github.com/CDLUC3/dmptool/assets/31976288/1b82b316-70a0-4bf3-8fea-228998e5633f)

Screens 6 to 11 refer to the template that I cannot edit.

![screen_customize_6](https://github.com/CDLUC3/dmptool/assets/31976288/a654444c-2dc1-402f-b680-87e27eccb920)

![screen_customize_7](https://github.com/CDLUC3/dmptool/assets/31976288/67b92279-0a45-485b-bb9d-be51ca66421e)

![screen_customize_8](https://github.com/CDLUC3/dmptool/assets/31976288/bf268c96-8be3-42ff-bec8-8469a1a43fb7)

![screen_customize_9](https://github.com/CDLUC3/dmptool/assets/31976288/9ec4d23d-a59c-47d6-9370-908927b0d156)

![screen_customize_10](https://github.com/CDLUC3/dmptool/assets/31976288/a1794df8-0da8-477f-99cd-075c8d6f9d5e)

![screen_customize_11](https://github.com/CDLUC3/dmptool/assets/31976288/88845f64-edc5-4f3d-a81d-b8b8d9d86089)

I am available for clarification.

Best Regards

**Comment by fcsousaunifesp** [comment]
Reviewing screen 11, for 11A.

![screen_customize_11_A](https://github.com/CDLUC3/dmptool/assets/31976288/484690b6-221d-4a3d-abe8-a5f7e0fa27e1)

Best Regards

Flavio Castro de Sousa

**Comment by fcsousaunifesp** [comment]
See that on screen 11A, 2 items are not available.

Best Regards

Flavio Castro de Sousa

**Comment by fcsousaunifesp** [comment]
Hi @briri 
When accessing the database, I verified that the modifiable column, in the sections table, the values ​​referring to this phase are unmarked.
Would this be the fix, or does it bring other impacts?

Best Regards

Flavio Castro de Sousa

**Comment by briri** [comment]
Hi Flavio changing the 'modifiable' column may bring other undesired impacts.

Customizations are not the same as a regular template. For example, when an institution's administrator wants to customize a funder template, they can add their own 'example answer', their own 'guidance', OR they can add a new section that has it's own questions. They can NOT change the original questions.

Here is our documentation for how customizations work: https://github.com/CDLUC3/dmptool/wiki/customizing-funder-templates
