### ISSUE TITLE
Review the latest ROR API changes

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#507]
Review the latest ROR API changes and see if there is anything we should change with our current implementation or if there are new metadata fields we can use to enhance people's experience

https://ror.org/blog/2023-09-14-beta-test/

**Comment by briri** [comment]
Review complete. Nothing in the new schema that will break anything we are currently doing. There are some new metadata elements that may be useful going forward

**Comment by briri** [comment]
Received an error from the automated ROR update from the DMPTool stage system. 

Need to verify that the script is correctly pulling the ROR file based on the recent Zenodo changes

**Comment by briri** [comment]
Probably need to prioritize this one @mariapraetzellis. We haven't had a successful ROR update in months.

**Comment by bofstein** [comment]
Pairs with https://github.com/CDLUC3/dmsp_aws_prototype/issues/84
