### ISSUE TITLE
Plans Downloaded as Word Documents Have Bad Formatting

### ISSUE THREAD

**Issue by igwink** [CDLUC3/dmptool#534]
**What version of the DMPRoadmap code are you running? V. 5.9**

When I attempt to download a plan (tested using the NIH DMSP template) as a Word document, the resulting format is in all caps for questions and deletes many spaces in between words (see attached WordDocFormatting image),
![WordDocFormatting](https://github.com/CDLUC3/dmptool/assets/35858990/074fb673-47b8-4623-98da-3023bc78cb72)

Downloading the same plan as a PDF results in cleaner formatting (see attached PdfFormatting image). 
![PdfFormatting](https://github.com/CDLUC3/dmptool/assets/35858990/d7e8ffb4-74af-4e56-ba87-07fbd1d91ed2)

Ideally for the NIH plan, there would be an option to format the resulting Word document in the style of the NIH [DMSP format page](https://grants.nih.gov/grants/forms/data-management-and-sharing-plan-format-page), though admittedly that's a separate issue.

**Comment by igwink** [comment]
This problem is still occurring for me. Has anyone else experienced it?

**Comment by mariapraetzellis** [comment]
Hi, @igwink, the question text in the DMP is intended to be in all caps when a plan is downloaded. If you do not want to see the question text included in the downloaded version you can uncheck the "include question text" check box on the Download page.
 
The extra spaces in the Word version of the downloaded doc may be dependent on what version of Word & what OS you are working on (PC/Mac). I tested it on my side and there are no extra spaces.
