### ISSUE TITLE
Filters on public plan page not working as expected

### ISSUE THREAD

**Issue by wdahdul** [CDLUC3/dmptool#535]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

**Expected behaviour:**
I was expecting to be able to filter on Funder and Subject here: https://dmptool.org/public_plans?search=&sort_by=title 

**Actual behaviour:**
Funder and Subject filters display "0" despite all 1,195 plans displayed in the panel to the right. 
 
**Steps to reproduce:**

**Comment by mariapraetzellis** [comment]
This was fixed in [v5.10]( https://github.com/CDLUC3/dmptool/releases/tag/v5.10)
