### ISSUE TITLE
Upload changes

### ISSUE THREAD

**Issue by magicalmary** [CDLUC3/dmptool#537]
Changes for the "Uploads" page:
1. Change title from "Uploads" to "Pilot Upload Projects".
2. Add below title: "Projects created via the upload of an existing DMP are listed in the table below, including their registration status and DOI (when generated)."
3. In the table, add a column for the pdf download icon (column title: 'DMP PDF'). PDF should open in a new tab
4. In the table, add a column for the DOI that is generated upon registration (column title: 'DMP ID'). Should open in a new tab.

**Comment by magicalmary** [comment]
@mariapraetzellis , please see suggested text change above and revise if needed. Thanks!

**Comment by briri** [comment]
@jupiter007 can you have a look at the DMPTool react-client code and start implementing these changes?

The new columns requested are already part of the data that React is receiving from the backend. 
- The DMP-ID should be a hyperlink but just display the DOI portion of it in the column (similar to how they appear on the public plans page ... see screenshot below for an example of a DMP-ID link)  
- The narrative URL should also be available already within the React code (it is downloadable on the project details page (after it's been uploaded of course). For the PDF icon, you should have access to the font awesome library

<img width="999" alt="Screenshot 2024-03-12 at 7 59 26 AM" src="https://github.com/CDLUC3/dmptool/assets/1204467/39a6f12b-b402-44b2-9e8a-ba65ff5b5149">

**Comment by jupiter007** [comment]
Hi @mariapraetzellis and @briri, do I implement the changes as specified in this Figma mock? https://www.figma.com/proto/Ei6s57Rls4HAUzkrVn3ptd/DMP-Upload-wireframes?page-id=0%3A1&type=design&node-id=217-107&viewport=-3691%2C-30293%2C0.83&t=oWum888MKGUsnTao-1&scaling=min-zoom&starting-point-node-id=217%3A107&show-proto-sidebar=1

**Comment by jupiter007** [comment]
@briri, per our discussion, I wasn't able to find the PDF url or the DMP ID in the API response.

**Comment by magicalmary** [comment]
Testing success!
