### ISSUE TITLE
[Bug] - Work on getting unit tests to work for react-client components

### ISSUE THREAD

**Issue by jupiter007** [CDLUC3/dmptool#544]
Currently, the unit tests for the react-client components cannot be tested using the normal test commands. Since the package.json file within the react-client was removed, there are missing libraries to get the tests to work.

Even when I installed those libraries into the package.json file at the root of the app, the tests still did not work. I believe there needs to be some configurations added in babel.config, or for jest, in order to get them to run.

**Comment by mariapraetzellis** [comment]
This will be solved in the new application when we finish the rebuild so we are closing this ticket.

**Comment by bofstein** [comment]
Closing for now because this code will eventually move to new app, would take a lot of time to invest in this for short term use
