### ISSUE TITLE
More info needed for Tooltip - "Submit for Review"

### ISSUE THREAD

**Issue by shlake** [CDLUC3/dmptool#55]
Comment/concern from one of our researchers:

They did not know who was reviewing the DMP. At 1st they thought the funder?

![screen shot 2014-07-17 at 3 27 47 pm](https://cloud.githubusercontent.com/assets/3809325/3618314/7a46013a-0de8-11e4-9cae-c2f902b9f743.png)

Suggestion to change the wording on the tooltip:
     _Submit your plan for an informal review from your institution._

**Comment by mxsstrong** [comment]
This appears to have been a tool tip that was on the DMP Preview page.  However there is no longer a tool tip here.  So not sure if this is still an issue.

**Comment by stephaniesimms** [comment]
tooltip exists on DMP Preview page. other open issues pertain to customizing auto-generated emails to notify researchers about who is conducting reviews and when to expect a response #139 #159
