### ISSUE TITLE
Upload bugs

### ISSUE THREAD

**Issue by jupiter007** [CDLUC3/dmptool#554]
A number of bugs were identified during testing of the Upload pages.

This doc was created to summarize the findings: https://docs.google.com/document/d/1I3GDjGG1A9LQ6zhMYa965zCLPsynH2n6DiM-tcMi3wk/edit#heading=h.z7o2gcfoywer

The issues with the highest priority are:
1) When adding Contributors on Stage, the "Save & Continue" button was sometimes not working.
2) Add messaging to user when a user tries to Add a Contributor without there being a Primary Contact. When this happens, the "Save & Continue" button does not work, but there is no messaging to tell the user what the issue is. We need to utilize the error message that we have to make sure user knows why they cannot continue.
2) The Repository selector showed lots of duplicates on production:
![image](https://github.com/CDLUC3/dmptool/assets/8452761/ae789485-1a3a-4a7e-bf27-83de0dab70f6)

Other issues include: (Please refer to link above to Google Docs for more details)
1) The value entered in search fields, like the Affiliation and Funder Typeaheads is included in the select dropdown.
2) Principal Investigator(PI) information entered into the search page does not get transferred to the Plan Details page
3) A Repository URL is required for plan submission on production, but not on stage
4) Should there be logic to list the largest funders first?
5) We need to add a "required" asterisk next to the "Repository URL" field. This field displays when a user enters a value that does not already exist in the dropdown list. It is not clear to the user that this field is required.

**Comment by jupiter007** [comment]
I noticed that the "Save & Continue" button issue on the Contributors page on Stage, is not working only when I have entered a Contributor without making them a Primary Contact. Maybe as a solution, we should message the user about it and disable the "Save & Continue" button?

**Comment by briri** [comment]
I added some fixes to change the order of the results in the typeahead fields. Affiliations (the ones with the most users are first), Funders (the ones with the most plans are first), Repositories (the ones with the most use are first). If the search term matches the name of one of the results (e.g. `dryad`, then only the record for `Dryad` is returned).

We will need to look into cleaning up the duplicate repository records
