### ISSUE TITLE
Issues with PDF upload control 

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#563]
We discovered a few issues with the PDF upload portion of the Pilot project pages while investigating issue #562

1) When uploading a file that is not a PDF, the UI is not displaying the error message back to the user. The API responds with:
`API V3 ERROR: status: bad_request, errors: ["Narrative must be a PDF document"]`. The user should be presented with the message so that they know what happened and how to correct the issue.

2) The Rails app is limiting the size of the PDF to 350Kb but the UI indicates that it allows up to 1MB. We should update Rails to be the same.

3) It appears as though the 'Remove PDF' checkbox is not working.

**Comment by bofstein** [comment]
The top two are two are now fixed but the Remove PDF button, while appearing on the page, does not seem to work.  After selecting it and hitting Save & Continue, the PDF remains.


![Image](https://github.com/CDLUC3/dmptool/assets/23406931/5559d033-9369-4790-a561-39450a96a58e)

**Comment by jupiter007** [comment]
@briri I made a small update in **drafts_controller.rb** to remove the "`narrative`" from the "`draft_data`" in the **metadata** when "`remove_narrative`" param is present.

That, along with the existing code that calls "`dmp.narrative.purge`" to remove it from the **active_storage_attachment** table does remove the PDF. However, I am able to register my plan even without a PDF. Is that expected?

Here's a link to my changes: https://github.com/CDLUC3/dmptool/tree/bug/narrative-pdf-is-not-removed-from-upload-plan

**Comment by briri** [comment]
Oh great! thanks for looking into this.

Yes, it's ok to register without the PDF. For the pilot we're really just interested in the metadata at this point. We should probably require it though in the new system when people use the 'Upload' scenario.
