### ISSUE TITLE
DOIs registered from new DMP Upload page are invalid for DataCite

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#569]
The DOIs that we register from the new DMP Upload page have metadata that DataCite is rejecting. EZID accepts the metadata and does not return an error. 

```
<creator>
<creatorName nameType="Personal">Jane Doe</creatorName>
<nameIdentifier>http://jdoe@example.com/</nameIdentifier>
<affiliation affiliationIdentifier="https://ror.org/https://ror.org/1234567" affiliationIdentifierScheme="ROR"> University of Example </affiliation>
</creator>
```
The issue is 2 parts:

The duplicated `https://ror.org/` in the affiliationIdentifier is happening within the new DMP Upload pages. The typeahead is prepending the base URL without first checking if it already exists.

The `<nameIdentifier>` requires a `nameIdentifierScheme` to be specified, so we will need to update the Lambda that calls EZID so that excludes this field when we do not have an ORCID

**Comment by briri** [comment]
Tested and things look good on stage. Will need to do a quick pass to fix affected records in prod and in EZID.

**Comment by mariapraetzellis** [comment]
@briri Do we still need to fix the affected records or can we close this?

**Comment by briri** [comment]
This was fixed
