### ISSUE TITLE
Grant URL is duplicated on landing page

### ISSUE THREAD

**Issue by magicalmary** [CDLUC3/dmptool#571]
1. Login to production instance.
2. Go to landing page for 'upload' pilot project:  https://dmphub.uc3prd.cdlib.net/dmps/10.48321/D14F38aa13
3. Under 'Funding status and sources for this project' in the 'Grant' field, the grant URL is presented twice. See screenshot below.

![Screenshot 2024-04-11 at 2 16 20 PM](https://github.com/CDLUC3/dmptool/assets/84808621/51c989c8-98fa-4013-a0ee-1665324ea3ea)

**Comment by bofstein** [comment]
This is now fixed


![Image](https://github.com/user-attachments/assets/868c88d9-db49-45ba-8a0a-53b73f19b8b5)
