### ISSUE TITLE
Issue with Contributors links on uploaded project landing page

### ISSUE THREAD

**Issue by magicalmary** [CDLUC3/dmptool#572]
1. Login to production instance.
2. Go to landing page for 'upload' pilot project: https://dmphub.uc3prd.cdlib.net/dmps/10.48321/D14F38aa13
3. Under 'Contributors to this project' the following links are broken:
a. 'University of Colorado Boulder' which goes to (https://ror.org/https://ror.org/02ttsq026)
b. ORCID '0000-0002-6917-5365' which goes to (https://dmphub.uc3prd.cdlib.net/dmps/10.48321/0000-0002-6917-5365)

All other links on the landing page work as expected.

**Comment by briri** [comment]
this has been fixed and deployed to prod
