### ISSUE TITLE
TinyMCE Cloud Subscription - usage based billing

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/dmptool#573]
On May 14, 2024, TinyMCE is launching a usage-based billing model to enforce the Editor Load limits associated with our Cloud editor subscriptions. This change will be effective in your account for the next full monthly period beginning after May 14 (based on your specific subscription date).

- [ ] confirm if DMPTool is using cloud-based TinyMCE subscription 
- [ ] if not, use the open-source self-hosted version of TinyMCE, if possible to avoid further charges
- [ ] review usage as provided in the email from TinyMCE
- [ ] if we need to purchase the cloud-based subscription will need to work with vendor and go through procurement

**Comment by jupiter007** [comment]
Hi @marisastrong and @mariapraetzellis. The DMPTool is currently using the [tinymce npm package](https://www.npmjs.com/package/tinymce), which is `open source` and `free`. It is installed with the other node modules from package.json.

It appears that all the tinymce plugins we are using in the app currently are also free. Here is a list of the plugins we are currently using:

- table
- lists
- image
- autoresize
- link
- advlist (i.e. '[List Styles](https://www.tiny.cloud/docs/tinymce/latest/advlist/)' )

These are all included as part of the list of free plugins, per [TinyMCE's documentation](https://www.tiny.cloud/blog/tinymce-free-wysiwyg-html-editor/#h_68924433315851710993317740)

**Comment by mariapraetzellis** [comment]
Excellent! Thank you @jupiter007
