### ISSUE TITLE
Clicking on 'DMP ID' DOI takes you to an empty landing page (pilot project)

### ISSUE THREAD

**Issue by magicalmary** [CDLUC3/dmptool#575]
**To Reproduce**
1. Login to production instance of DMP Tool.
2. Change our profile's organization to 'University of California, Riverside (ucr.edu)'
3. Go to 'Upload Plan' dashboard
4. Go to project 'EAGER: Dual magnetic resonance and optical modalities for image-guide early detection, staging, and resection of ovarian tumors'
5. Click on DOI 'https://doi.org/10.48321/D1FFBFF8FE'
6. The landing webpage quickly shows the header, "Loading..." then a blank "Contributors to this project," then loads an empty webpage

**Expected behavior**
The landing page for the project is returned with the high-level details outlined.

The user, Katherine Koziar sent the following additional details and error messages:

I've replicated the same issue in three browsers (chrome, edge, firefox).  The other DMPs we uploaded will open fine using the DOI (although, they also have a manifest error in the developer console).
 
Firefox developer mode shows javascript errors:
TypeError: n is null                           main.e613dc0e.js:2:138186
   it https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    Ea https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    El https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    wu https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    yu https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    gu https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    au https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    ou https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    k https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    P https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
and
Uncaught TypeError: n is null        main.e613dc0e.js:2:409699
    it https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    Ea https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    El https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    wu https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    yu https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    gu https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    au https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    ou https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    k https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
    P https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js:2
~~~~~~~~~~~~~~~~~~
two source map errors
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://dmphub.uc3prd.cdlib.net/static/css/main.820482f8.css
Source Map URL: main.820482f8.css.map
 
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://dmphub.uc3prd.cdlib.net/static/js/main.e613dc0e.js
Source Map URL: main.e613dc0e.js.map
~~~~~~~~~~~~~~~~~~~~
Chrome/edge errors are
Manifest: Line: 1, column: 1, Syntax error.   manifest.json:1
 
TypeError: Cannot read properties of null (reading 'affiliation_id') react-dom.production.min.js:189
    at it (contributors.js:35:13)
    at Ea (react-dom.production.min.js:167:137)
    at El (react-dom.production.min.js:290:337)
    at wu (react-dom.production.min.js:280:389)
    at yu (react-dom.production.min.js:280:320)
    at gu (react-dom.production.min.js:280:180)
    at au (react-dom.production.min.js:271:88)
    at ou (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.P (scheduler.production.min.js:14:128
 
Uncaught TypeError: Cannot read properties of null (reading 'affiliation_id')
react-dom.production.min.js:283
    at it (contributors.js:35:13)
    at Ea (react-dom.production.min.js:167:137)
    at El (react-dom.production.min.js:290:337)
    at wu (react-dom.production.min.js:280:389)
    at yu (react-dom.production.min.js:280:320)
    at gu (react-dom.production.min.js:280:180)
    at au (react-dom.production.min.js:271:88)
    at ou (react-dom.production.min.js:268:429)
    at k (scheduler.production.min.js:13:203)
    at MessagePort.P (scheduler.production.min.js:14:128)

**Comment by jupiter007** [comment]
@magicalmary this is happening because of the way we are checking for whether affiliation_id exists before trying to use it to assemble a link.

I made a bug fix and created a pull request in the "dmsp_aws_prototype" repo: https://github.com/CDLUC3/dmsp_aws_prototype/pull/129

**Comment by magicalmary** [comment]
Verified fixed - thank you!
