### ISSUE TITLE
Formatting issues on DMP ID landing pages

### ISSUE THREAD

**Issue by magicalmary** [CDLUC3/dmptool#578]
One of the pilot team members noted some formatting issues on the 'landing pages' for projects registered using DMP Tool:

1. Go to 'DMP ID' landing page in the 'Upload Plan' table, such as https://dmphub.uc3prd.cdlib.net/dmps/10.48321/D1FFBFF8FE
2. The width for the 'Planned outputs' text section is smaller than the width of the 'project description' section, and so the text looks misaligned on the page. Specific example provided:  https://dmphub.uc3prd.cdlib.net/dmps/10.48321/D18H0M
(Note: the provided example was created using 'create plan' on the main dashboard; I cannot find an example in the 'Upload plan' DMSP table currently. Do these 'reports' have the same formatting? If not, I can log this as a separate issue.)
3. In the 'Project details' section, the date fields use 'DD Mon YEAR' formatting. For example:
Project Start: 01 Sep 2020
Project End: 31 Aug 2025
Created: 26 Apr 2024 11AM
Modified: 29 Apr 2024 12PM
User suggests we use the standard ISO 8601 format:  DD-MM-YYYY

![2](https://github.com/CDLUC3/dmptool/assets/84808621/5405196e-c7e1-438d-ad01-3e594267081c)
![3](https://github.com/CDLUC3/dmptool/assets/84808621/4a39df72-640d-485e-952a-0b2cb9e88eaa)

**Comment by briri** [comment]
The `DD-MM-YYYY` date format can be confusing based on where the view is located. We use `MM-DD-YYYY` in the US but most other countries use DD-MM-YYYY so `06-07-2024` can be confusing.

Did the user specify a reason why they think we should change it? In the JSON version (that would be used to communicate with other systems) we use the ISO8601 standard for date formatting. E.g. `YYYY-MM-DDThh:mm:ss+hh:mm`.

**Comment by mariapraetzellis** [comment]
We've decided to leave the date format so we do not confuse European users.

**Comment by jupiter007** [comment]
@magicalmary the width of the content in "Planned outputs" is different from the "Project description", because the content under "Planned outputs" is actually in an HTML list (i.e., using `<ul><ul/>` tag), whereas the content under "Project description" is in a normal `<p> `paragraph tag. 

I believe the narrower width will make it more readable when there are multiple items in the list.

**Comment by magicalmary** [comment]
Consulted with Juliet, and we noted the 'Planned Outputs' landing page descriptions are included and can take up a lot of space (depending on the text entry). Can this be removed, and replaced with the table of outputs as displayed in a downloaded DMP, @briri ? (see attachment)

![Screenshot 2024-05-15 at 10 51 19 AM](https://github.com/CDLUC3/dmptool/assets/84808621/fa246865-1e17-43ee-9209-19f03124e47d)

**Comment by jupiter007** [comment]
@mariapraetzellis, I know you are busy, but when you get the chance, can you weigh in on what you think about displaying Planned Research Outputs in a table format?

For now, I am going to mark this as blocked

**Comment by mariapraetzellis** [comment]
@mariapraetzellis Will review this and comment with a final decision on implementation.

**Comment by mariapraetzellis** [comment]
For now let's leave the Planned Outputs section formatted as is. The current format works well with newly created DMPs (not uploaded) & I think will work with most uploaded plans as well. However, if we see that its a problem we will reopen this issue and transform the Planned Outputs section into a table.
