### ISSUE TITLE
Funder not showing up as 'Primary Funding Organization'

### ISSUE THREAD

**Issue by timvdstap** [CDLUC3/dmptool#581]
**Describe the bug**
The 'Tula Foundation (tula.org)' does not show as an option under 'Select the primary funding organization' when creating a DMP. However, it does show up under 'Funder' in the Project Details page. Our current work-around is to select 'No funder associated with this plan or my funder is not listed' in the first stage.

**To Reproduce**
1. Select 'Create New Plan'
2. Populate 'Select the primary funding organization' with 'Tula Foundation'

![image](https://github.com/CDLUC3/dmptool/assets/62965116/ff6a6b13-21aa-4094-b2e6-ae3f25fbf697)

However, as shown in image below, it does show up in the following page:

![image](https://github.com/CDLUC3/dmptool/assets/62965116/c5dd1e89-dbab-4fbd-a612-eae65f1d0fdd)

**Expected behavior**
I would expect Tula Foundation (tula.org) to show up in the list of option for primary funding organization.

**Comment by mariapraetzellis** [comment]
@timvdstap If I understand this issue correctly, the reason the Tula Foundation does not show up as an option for "Select the primary funding organization" when creating a new plan is that there is no template for the Tula Foundation in the DMP Tool. The field for "Funder" on the project details page pulls from a [directory](https://ror.org/0029jxk29) of all research organizations. 
I hope that helps! If I've misunderstood the issue let me know.

**Comment by timvdstap** [comment]
@mariapraetzellis Thank you, that makes sense given that I do see 'Hakai Institute' be available as an option under 'Select the primary funding organization' (and there is a Hakai Institute Data Management Plan Template).

**Comment by timvdstap** [comment]
@mariapraetzellis Would that not mean however that when I select 'Hakai Institute' as the primary funding organization, that I should see our Hakai Institute Data Management Plan template show up as an option below it? Or does that not show up as we only have a single institutional template, and it defaults to that?
