### ISSUE TITLE
unable to register upload plan (pilot project)

### ISSUE THREAD

**Issue by magicalmary** [CDLUC3/dmptool#584]
1. Login to DMP Tool production instance
2. Member is from "University of California, Riverside"
3. User went to "Upload plan" feature and uploaded document and entered project name ("PPoSS: Planning: Dynamic Big Graph Store for High-Throughput and Secure Distributed Query Processing")
4. User completed all sections, and made sure PIs and primary contact were designated. 
5. When she clicked 'Register and Return to Dashboard,' she received this error: "There was a problem registering your plan. Please try again later."
6. I checked her data entry and nothing appeared unusual except that there are 5 PIs listed (not sure if there is a limit). I tried to register the same DMP, and received the same error message (sorry, I'm working a conference and cannot go through all steps right now).

**Comment by briri** [comment]
Manually addressed the issue in the UI. The repository URL had leading blank spaces which was causing the URI library to fail to parse the URL string.

Need to update the code so that it always trims blank spaces before trying to validate the URL.
