### ISSUE TITLE
PDFs of public plans not displaying on the DMP Hub

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#597]
A user reported two DMP IDs, which are associated with publicly accessible plans that do not have PDFs accessible from the landing page. 

DMP ID: [10.48321/D1WK99](https://dmphub.uc3prd.cdlib.net/dmps/10.48321/D1WK99)
DMP ID: [10.48321/D17D0CBCE5](https://dmphub.uc3prd.cdlib.net/dmps/10.48321/D17D0CBCE5)

**Comment by briri** [comment]
This has been fixed.
