### ISSUE TITLE
DMP file upload button is not visible 

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#601]
The button to upload a PDF is not visible in the application. You can click into the Upload box and upload a PDF successfully. Brian checked the db, and the file exists and confirmed that the record does display the uploaded file. 

@jupiter007 and @briri will look into issues with the CSS. 

![Screen Shot 2024-06-11 at 3 21 25 PM](https://github.com/CDLUC3/dmptool/assets/27511575/1e3818dd-f3e9-4f1a-a1af-63ffdc47abf2)

**Comment by briri** [comment]
Looks like it is caused by [this line in the typeahead.scss](https://github.com/CDLUC3/dmptool/blob/2a771c18248574ef6dd9108ebb89681ac44d44f2/react-client/src/components/typeahead.scss#L5)

**Comment by magicalmary** [comment]
ASU has just reported this issue as well - see screenshot.
![ASUbug](https://github.com/CDLUC3/dmptool/assets/84808621/cfe08ab9-e9ef-4b8d-b012-b4a06e7a0700)
