### ISSUE TITLE
Add/create a Get Started page

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#63]
Stub issue for wireframe @rhu001 
When user clicks Get started they should be taken to a new page with contextualized info about signing in, creating an account, finding resources (Funder Requirements, Public Plans, Quick Start Guide)

UPDATE: this will be done post MVP. potentially create a new static page. for now clicking Get Started button will take user to Sign In modal.

**Comment by rhu001** [comment]
Here is an initial draft. https://docs.google.com/document/d/1PqSBqtIcSmo_ReuB8toJNpaLo1niVcAz-4D16Lzjigs/edit#
I might add in a bit more info but @stephaniesimms please review in the meantime.

**Comment by briri** [comment]
Can this one be closed out @stephaniesimms?

**Comment by stephaniesimms** [comment]
i think so
