### ISSUE TITLE
Update entityID for University of Denver

### ISSUE THREAD

**Issue by marisastrong** [CDLUC3/dmptool#636]
Hi Brian and Marisa,

I’m one of the IdP administrators at the University of Denver.  I came across your names as a technical resources for DMP (https://dmp.cdlib.org/) and was hoping you could help.
 
We are changing our primary identity provider. I noticed that DMP is configured with the IdP we are moving away from (mamiwata.du.edu/idp). We would like to switch DMP from using this IdP and switch it to use our new and primary IdP (https://login.du.edu/idp). Would you be able to assist or be able to point me in the right direction?

Our new IdP is also InCommon federated so we are hoping it’s a quick and painless transition
 
Please let me know if you need any additional information.
Brent Goebel
Manager, Digital and Technology Solutions

Information Technology

**Comment by bofstein** [comment]
Created as [Freshdesk ticket 141300](https://cdl.freshdesk.com/a/tickets/141300), I will track and follow up there.
