### ISSUE TITLE
Cannot select a template if no funder is selected

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmptool#640]
**Describe the bug**
If no funder is selected, no option comes up to select a DMP Template

**To Reproduce**
1. Sign in to DMP Tool (I used stage)
2. Go to Create Plan
3. Add in any research org, or select none
4. Select that there is no specific funder
5. Observe that no option comes up to select a DMP Template

**Expected behavior**
After no funder is selected, a new option should appear to select a DMP Template from a searchable list, like in this example from someone's institution:
![image](https://github.com/user-attachments/assets/629a56c5-ec1d-4206-83f4-fb3f77a4173b)

**Screenshots**
Note no search box here to find a DMP Template
![image](https://github.com/user-attachments/assets/640bd8a8-f3d0-4996-871e-17308f52994d)

This is the template that's been chosen for me each time, not sure what affects it.  I don't see a way to change the template once the plan is created either.
![image](https://github.com/user-attachments/assets/ef370c00-417c-4f4f-bf4a-7a88340498a5)

I confirmed the research org that reported the issue does have at least one published template
![image](https://github.com/user-attachments/assets/432334c7-9592-4c9b-ba56-7486a52f6ee1)

**Additional context**
Two tickets have bene sent in about this (one noting other colleagues facing the same issue), the earliest from July 12th - maybe related to our new version released just before then?

**Comment by briri** [comment]
I switched the visibility of their published templates to 'Organizational' and they now appear for their users
<img width="926" alt="Screenshot 2024-08-02 at 11 40 42 AM" src="https://github.com/user-attachments/assets/d834098f-c0f0-434f-829d-d4a8cd15fef2">

We can discuss the (ill)ogic behind all of this when you're back next week.

**Comment by bofstein** [comment]
I will message to the ticket writers about the changes needed

Hard to fix in current system, will change in rebuild
