### ISSUE TITLE
Debug eLabNext account issue

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmptool#648]

**Comment by briri** [comment]
It looks like the sign in pages that are used as part of the OAuth2 workflow were not properly updated when we rolled out the new homepage redesign last January. 

The doorkeeper managed views cannot make use of partials from other directories so we will need to copy over the functionality from the current sign in page. We should also tweak the CSS classes a bit as it seems to have lost margins and button formatting.

**Comment by briri** [comment]
Closing this in favor of #651
