### ISSUE TITLE
[Bug] Investigate OAuth issue faced by eLabNext

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmptool#651]
An ELN that has an integration with DMP Tool is experiencing auth issues.  They are unable to log in to their accounts through their desktop application that uses the DMP Tool, but can log in with the same account on the website..
![Image](https://github.com/user-attachments/assets/08e9de0c-4035-42ab-9f1c-88acf97ba694)

Note they sent some videos of the situation that I cannot attach, but are available in email to myself and Brian.

**Comment by briri** [comment]
multiple issues here. 
- The WAF is blocking some of the traffic to these OAuth routes, so need to modify the WAF rules to allow access
- Doorkeeper and Devise gems have been upgraded at some point in the past and broken the functionality
- Doorkeeper views seem to be unable to access the compiled CSS files
- Need to tie the current system's authentication into the OAuth2 authorization flow
