### ISSUE TITLE
Ensure Juliet has permissions to push current DMP Tool changes

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmptool#655]
Should be done before October 7th when Brian is going out of town

Puppet hiera

**Comment by jupiter007** [comment]
I met with Ashley to go over a practice release to stage. I was able to ssh into both DMP servers, update the "revision" version for a dmptool tag in the [uc3-ops-puppet-hiera](https://github.com/CDLUC3/uc3-ops-puppet-hiera) repo, and deploy the change to stage.

I also practiced rolling that change back on both servers.
