### ISSUE TITLE
Notification emails for review requests not being sent to Admins

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmptool#665]
A user (org admin) reported that they had not been getting emails notifying them of DMP review requests.  They reported it for a plan on November 20th, and then repro'd it with a test on November 25.

I tested myself requesting feedback from UCOP, which should go to the DMP Email, and also did not get an email about a feedback requests, though I see the request in my list of notifications in UCOP.

![Image](https://github.com/user-attachments/assets/1d38d87c-be01-41e1-b38f-b934b51f55e7)

Just based on timing, it could be related to our Rails upgrade but no idea for sure.

**Comment by briri** [comment]
Turned out to be a missing SSM parameter (the name changed from `do_not_reply_email` to `organization_do_not_reply_email`). Updated on both prd and stg and restarted the system.
