### ISSUE TITLE
Double numbering sections on export

### ISSUE THREAD

**Issue by jwarbeau** [CDLUC3/dmptool#67]
Is there a way to fix the “double” numbering of sections that happens in the PDF or RTF export (we have one more level of instruction than the template currently supports and so the numbering format gets out of sync)?

Example of PDF Export:

See IMG 3 below:
![img 3_output formatting](https://cloud.githubusercontent.com/assets/7872205/3735410/ef1a9d38-1723-11e4-9a46-61e1be53f93a.png)

**Comment by mxsstrong** [comment]
from sherry:

**Comment by mxsstrong** [comment]
Just one tweak on the DMP Preview output (RTF and PDF look good): the sub-sections have increasing larger text size.

When using this template:
https://dmp2-staging.cdlib.org/requirements_templates/79/requirements

Look at the preview output for this DMP, to see what I mean:
https://dmp2-staging.cdlib.org/plans/1416/preview
