### ISSUE TITLE
Missing help text for "Add Sample Plan"

### ISSUE THREAD

**Issue by jwarbeau** [CDLUC3/dmptool#71]
In Internet Explorer 9, in the DMP Template Overview, “Add Sample Plan” doesn’t seem to work—just gives two text boxes, but no cues/instructions in the boxes like you have in Chrome—THIS MAY BE AN IE COMPATIBILITY ISSUE specific to SI—not sure.  See IMG 6 below:
![img 6_add sample plan](https://cloud.githubusercontent.com/assets/7872205/3735509/d59c4a72-1724-11e4-876e-680083767609.png)

**Comment by shirin238** [comment]
@mxsstrong I have access to IE8 and there are no issue there.
