### ISSUE TITLE
Test/update links in email notices

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#74]
contact email missing in screenshot 1 "contact us at ___"

update/redirect Help page to For administrators in email below...this may just be an issue for static pages and I think only Help pages, but need to check emails to verify

1 - Request feedback email. Contact email missing.
![screen shot 2018-02-21 at 7 59 10 pm](https://user-images.githubusercontent.com/12703638/36519711-e2edb578-1741-11e8-9f54-6bab4ea7f2dd.png)

2 - 
![screen shot 2018-02-14 at 10 01 30 pm](https://user-images.githubusercontent.com/12703638/36242794-c5869924-11d2-11e8-952a-26b6bc1a2c72.png)

**Comment by briri** [comment]
have we determined where this page will live?

**Comment by stephaniesimms** [comment]
this email caught my eye because we haven't 100% figured that out yet. for now you can point it to the For Administrators page. that's probably the right one. which will then take them out to the github wiki where the help actually lives.

**Comment by stephaniesimms** [comment]
duplicate issue
