### ISSUE TITLE
Copyright Statement on Public DMPs

### ISSUE THREAD

**Issue by shlake** [CDLUC3/dmptool#84]
Concern for people downloading public DMPs and using them without realizing DMPs are copyrighted by their creator.

Places to add copyright info:

* On page listing public DMPs: https://dmptool.org/public_dmps
* On the PDF that is downloaded (there is already a footnote added with date, a copyright statement should also be in the footnote)
* When creating a DMP on the "Copy an Existing DMP": https://dmptool.org/plan_template_information

**Comment by stephaniesimms** [comment]
Solved by metadata cover sheet
