### ISSUE TITLE
Replace "Answered by" with generic "Autosaved" message on write plan page

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#90]
Usability testing revealed that users are confused by the "Answered by message and timestamp" that appears when answers on the write plan page are autosaved. Some think this means they're done answering the question.

Suggestion to replace the message with a generic "Autosaved" - just need to think through implications for coauthored plans, but my guess is that it doesn't pose a problem. We don't indicate for current DMPTool users who has contributed which answers so a generic message should be fine. 

![screen shot 2018-02-21 at 6 52 15 pm](https://user-images.githubusercontent.com/12703638/36517780-640de0ce-1738-11e8-8353-a63e5ccc33a4.png)

**Comment by briri** [comment]
Hmm. Switching this to "Autosave" would I think be even more confusing. That section does several things currently.
- When you first load the page it displays the info above (or no message if no one has ever updated it)
- When you change the answer and then click 'save' or tab off of the field a `Saving ...` message briefly appears and is then replace by the message above. When you tab off its auto-saving.

Would it make sense to just leave the `Saving ...` message as is and remove the `Answered ...` messages?

**Comment by stephaniesimms** [comment]
adding a note to think this through post MVP
