### ISSUE TITLE
Accidental deletion of work

### ISSUE THREAD

**Issue by strasser** [CDLUC3/dmptool#97]
From an administrator: 

I've been trying to take the DMP Tool for a spin and now I'm creating an actual plan in the DMPTool. I've found that I'll fill out a section or do an additional edit and then absentmindedly click on another section of the plan and lose all of my work. I suspect I'm not the only one experiencing this. I'm so used to changes being saved or being prompted to save before leaving what I'm doing that I'm getting repeatedly burned by this. Is there a plan in the works to make this situation less of an issue?

**Comment by mxsstrong** [comment]
i'm not seeing this fix in stage.  if you click on a requirement it saves your work however if you click on preview it doesn't.

**Comment by stephaniesimms** [comment]
@briri merged Bhavi's code. Scheduled to deploy to production on 8 June 2016.
